### ISSUE TITLE
MKV cover art not displayed when written with taglib-sharp

### ISSUE THREAD

**Issue by jamerst** [Xanashi/Icaros#10]
Cover art embedded in files tagged by taglib-sharp isn't displayed in Windows Explorer. This appears to be caused by the name of the attached artwork, as taglib-sharp names it as "FrontCover.jpg", but the standard name is "cover.jpg".

The taglib-sharp name isn't compliant with [these](https://matroska.org/technical/cover_art/index.html) guidelines, but the thumbnail displays fine under Linux, so surely it should work with Icaros too?

I'll create an issue for taglib-sharp too, but I think adding support for these different cover names is a worthy enhancement.

**Comment by Xanashi** [comment]
Agreed. I'll add "FrontCover.jpg" as an accepted cover name to Icaros in the upcoming release.
That way we can make Icaros compatible with files already tagged by taglib. 

Making taglib compatible with the MKV specifications is a pretty good idea too, though,
for future releases. :)

**Comment by Xanashi** [comment]
Do you have a sample file? Just need to confirm that it works. ;)

**Comment by Xanashi** [comment]
Thank you!
These files should show proper covers now from the next release and forward.
You might have to clear your thumbnail cache or refresh the thumbnails of these specific files
before it works. :)
