### ISSUE TITLE
Thumbnail Offset isn't working

### ISSUE THREAD

**Issue by sidsharths1245** [Xanashi/Icaros#100]
So I record a lot of videos with a movie clapper in the first few seconds, this helps me organize the videos easily. I want the first frame to be the thumbnail of the video files, MP4, MOV, MKV etc. I am attaching a screenshot of the settings I am currently using. Do i need to change something? Or is this a bug?

![IcarosConfig_y1f3tMsHwN](https://github.com/Xanashi/Icaros/assets/64619769/54b6102a-4259-48a7-9aec-fac1521587ef)

**Comment by Xanashi** [comment]
Try setting the offset to 0% (you can disable 'Prefer Timestamp' or set that to 0 as well). 
This should give you the very first frame of the file.
If you set anything above 0, Icaros will try to seek to that % or timestamp with FFmpeg and that will in most cases go past the first frame.

**Comment by Xanashi** [comment]
I'm just closing this ticket for now, but you're welcome to reopen it if needed.
