### ISSUE TITLE
MKV properties: "Comments" and "Contributing artists" fields are not displaying unicode characters properly

### ISSUE THREAD

**Issue by vermian** [Xanashi/Icaros#101]
Using Icaros v3.3.2, Windows 10 x64. MKV properties are enabled in Icaros. MKV files with unicode in the "Comments" and "Contributing artists" fields are not displaying the unicode characters properly. I haven't checked other fields that might be affected by this. The title field is correct though.

![Icaros_unicode_issue](https://github.com/Xanashi/Icaros/assets/17242410/8fafd812-51d5-44a1-b674-0e2185dace69)

Comparison with correct unicode in MPC-HC in image - fields are named "Author" and "Description".

![Icaros_unicode_issue_correct_in_mpc-hc](https://github.com/Xanashi/Icaros/assets/17242410/20e756a1-0a98-440b-b2bd-7c8348b3fbe1)

Relevant unicode text to test with: 
ありさMMDch_ホロライブメイン
ー赤井はあとー (links omitted)【Music】：やほー。【ホロライブ/赤井はあと】（チャンネル登録１５０万人突破後最後の曲）

**Comment by Xanashi** [comment]
I’ll make sure to check it out.

**Comment by Xanashi** [comment]
This should be fixed in 3.3.3 Beta 1:
https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b1

Let me know if it works.

**Comment by vermian** [comment]
Yes, seems to work properly now. Thank you.
![icaros unicode fixed](https://github.com/Xanashi/Icaros/assets/17242410/b1e4dc79-2d89-4d2e-9dbe-f79c788531ec)

One last question if you don't mind: is there a way to manipulate the star rating for mkv files? I don't know which application even supports editing that.

**Comment by Xanashi** [comment]
Thank you, so glad to hear it.

I use MP3Tag, it's free and a great software. 
The name is a bit deceptive in that it does support quite a few other filetypes besides mp3, including mkv.

Rating isn't a default tag field, but it can be added using the menus. 
The tag should be named "RATING" and it should contain a value between 1 and 5 (as in 1 to 5 stars).
It can, of course, be left empty.

**Comment by vermian** [comment]
Great, thanks for letting me know. I'll close the issue since it's fixed now.
