### ISSUE TITLE
The thumbnails for .pxz files are not visible properly

### ISSUE THREAD

**Issue by sidsharths1245** [Xanashi/Icaros#103]
How they should look:

![image](https://github.com/Xanashi/Icaros/assets/64619769/b3e6cdd7-c951-4a68-9c3f-52507b498c1f)

How they look:

![image](https://github.com/Xanashi/Icaros/assets/64619769/4d345173-dbef-47d3-955b-9b89f83e796a)

I think all elements of the file aren't visible.

**Comment by Xanashi** [comment]
I’m honestly surprised you get any thumbnail at all. 
It’s a propietary file format with no public file specification available anywhere as far as I can tell. And FFmpeg doesn’t support it. 
So it’s probably pure coincidence that you’re seeing anything in Explorer.

**Comment by sidsharths1245** [comment]
Thanks for responding :)
So I think .pxz is just another version of .psd files. They should have the same properties. I think that's why I was able to see this thumbnail without it being officially supported by Icaros. Can you try to implement it in the same way .psd is implemented? 

p.s. I really love Icaros. I had been searching for something similar for such a long time. You are life saviour sir. Much love

**Comment by Xanashi** [comment]
Thank you so much for the kind words. So glad you love it! 

You're welcome to send me a .pxz sample file, and I can take a look at it.

**Comment by sidsharths1245** [comment]
I am attaching the google drive link to a .pxz file (Github won't let me attach it). and also adding some information that might be useful to you.

[PXZ File](https://drive.google.com/file/d/1Mba2E6slDH7H-DGvmrh-T9nVNFGtrAW5/view?usp=sharing)

What is a PXZ file?
A PXZ file is a project file created by the Pixlr X, Pixlr E, or Pixlr M image editors. It is a Zip-compressed archive used to load a layer-based image in Pixlr. 

More Information
https://fileinfo.com/extension/pxz

p.e. I can see the base layer (Layer 1) in the thumbnail preview but the other layers on top aren't visible.

**Comment by Xanashi** [comment]
Thank you!
So this is basically just a zip file with a few images and data files. There is a 'thumbnail' image embedded, and if Icaros used that,
it would show a thumbnail with all the layers. So this would definitely be an easy fix from my end.
If all PXZ files are created the same way as the one you provided, I can definitely support them in Icaros.

**Comment by sidsharths1245** [comment]
Thank you so much Sir! I really appreciate it :)

**Comment by Xanashi** [comment]
This should be fixed in 3.3.3 Beta 1:
https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b1

Let me know if it works.

**Comment by sidsharths1245** [comment]
It is working. Thank you so much!! you're the best <3

**Comment by Xanashi** [comment]
You're very welcome. <3
