### ISSUE TITLE
jp2 support

### ISSUE THREAD

**Issue by 03302024** [Xanashi/Icaros#108]
I have a bunch of jp2 image files so I manually added jp2 extension to the list. However, I get black thumbnails for some of them. I can view them OK in XnViewMP. I was wondering if jpeg 2000 is fully supported.

**Comment by 7eventech77** [comment]
JPEG2000 would be nice in the future, it also goes hand in hand with PDF thumbnailing since Adobe Acrobat supports that as a image codec option.

**Comment by Xanashi** [comment]
Hi 03302024,
Could you send me some the files that produces black thumbnails?

**Comment by 03302024** [comment]
> Could you send me some the files that produces black thumbnails?

Here you are: https://archive.org/download/dr_pratts-high-test-plan-of-the-eastern-counties-and-the-midlands-12471000/12471000.jp2

**Comment by Xanashi** [comment]
Thank you! I'll look into it, and get back to you.

**Comment by 03302024** [comment]
Here is another one. It is a scan of a white page, but the thumbnail is shown in black.
[test file.zip](https://github.com/user-attachments/files/16325531/test.file.zip)

**Comment by 03302024** [comment]
Just a follow up for this feature request.

**Comment by Xanashi** [comment]
I looked into this and these files fail to decode with FFmpeg. 
So the FFmpeg jpeg2000 decoder is where this needs to be fixed.

**Comment by 03302024** [comment]
Thank you for looking into this issue. How we could inform FFmpeg people about this?

**Comment by Xanashi** [comment]
It's possible to report issues to the FFmpeg developers using their issue tracker:
[FFmpeg Issue Tracker](https://trac.ffmpeg.org/query?status=new&status=open&status=reopened&col=id&col=summary&col=status&col=type&col=component&col=version&col=time&col=changetime&report=12&desc=1&order=changetime)

They do have a few requirements for reporting bugs/requesting features, that must be read before creating a ticket:
https://ffmpeg.org/bugreports.html

**Comment by 03302024** [comment]
OK, thank you. I created an account there to report the issue. Hope it will be fixed soon.
https://trac.ffmpeg.org/ticket/11207

**Comment by 03302024** [comment]
I see there are bug reports over there from 14 years ago. Now, I am wondering if any other jp2 decoder could be used meanwhile?

**Comment by Xanashi** [comment]
The FFmpeg team fixes issues from that list every single day, so just because some tickets haven't been picked up by anyone in a long time, doesn't mean it's a common occurrence. Most tickets usually gets attention. 

I'm not that familiar with the jp2 format, and what alternative decoders exists, but I'm hoping FFmpeg will be able to decode these files in the near future. 

There is of course also a chance that these files were just incorrectly encoded, and may need to be re-encoded.

**Comment by 03302024** [comment]
OK, thank you for looking into this.
