### ISSUE TITLE
Add .avif to list of "Most known" thumbnail types

### ISSUE THREAD

**Issue by 7eventech77** [Xanashi/Icaros#109]
.avif is not added by default to "Most known" thumbnail types but works correctly when manually added. This would allow for people who would not know about this to automatically have .avif thumbnailing without having to manually add it after selecting "Most Known". Not sure if there was a reason it was not added. 

Thanks!

**Comment by Xanashi** [comment]
That is definitely just an oversight on my part. I tend to forget to update the presets with new filetypes.
Thank you for letting me know. It will be added in the next release.

**Comment by Xanashi** [comment]
Fixed in [3.3.3 Beta 3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b3).
