### ISSUE TITLE
 IcarosConfig.exe crash

### ISSUE THREAD

**Issue by Artins90** [Xanashi/Icaros#11]
Icaros is still working and generating thumbnails but when I try to access the configuration tool it opens and then crashes after 1 second.
I tried version 3.1.0 and 3.1.1 b2, I also tried to reinstall the DirectX runtime the other DX9 applications work.
This is the error report from event viewer:

```
Faulting application name: IcarosConfig.exe, version: 3.1.0.302, time stamp: 0x5d62852b
Faulting module name: d3d9.dll, version: 10.0.18362.329, time stamp: 0x1ac9a115
Exception code: 0xc000001d
Fault offset: 0x00000000000acd21
Faulting process id: 0xa08
Faulting application start time: 0x01d5655946e290de
Faulting application path: C:\Program Files\Icaros\IcarosConfig.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: dc6dcd8b-2106-4ec0-8322-5d597b6a6722
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Xanashi** [comment]
Hi Artins90,

That's a strange crash. Did any of the previous versions work without crashing, like versions before 3.1.0,
or are they all crashing? Did the crashes start recently or is this the first time you've opened IcarosConfig?
Last question, did you try and update your GPU driver?

**Comment by Artins90** [comment]
Hi Xanashi, thank you for your reply.

I have always had Icaros installed and active, the last installation was about 1 month ago right after a fresh installation of Windows, version 3.1.0.
The thumbnail generation is still working, today I wanted to modify a folder path for the thumbnail cache function and when I tried to open the configuration panel it crashed.
It might have been in this state for weeks without me realizing that there was an issu, I don't remember the last time I opened it, probably it was right after installing Icaros.

The Nvidia GPU driver is the latest version 436.15

**Comment by Xanashi** [comment]
What CPU and GPU models are installed in this system?
You don't happen to have a program called RivaTuner installed?

**Comment by Artins90** [comment]
Adding a profile in Rivatuner with detection set to none for the config panel fixed the crash.
Thank you.

**Comment by Xanashi** [comment]
Perfect! Glad to hear you got it working!
