### ISSUE TITLE
PSD file does not display the icon

### ISSUE THREAD

**Issue by CG-Bai** [Xanashi/Icaros#110]
![20240717164650](https://github.com/user-attachments/assets/0ff59d27-0d8f-4d93-a088-df1f987c51a0)
![20240717164809](https://github.com/user-attachments/assets/41bf7f2f-e4ee-4370-92de-9f3f16e9cce8)

**Comment by Xanashi** [comment]
Hi CG-Bai,

Icaros doesn't actually handle the icon overlays on thumbnails, except for the "Display icon overlays on thumbnails" option, which is just a shortcut to the Windows Folder option found in the View tab.

Try the suggestions found here: #58 and #49 
The IconOverlay value is probably set in either the .psd or image SystemFileAssociations keys.

**Comment by CG-Bai** [comment]
Thanks！
