### ISSUE TITLE
Question: Is .ogg files with opus codec and WebP embedded cover art thumbnailing a supported configuration?

### ISSUE THREAD

**Issue by 7eventech77** [Xanashi/Icaros#112]
My audio files use .ogg container and opus codec; I want to use WebP as the codec for the cover art that is thumbnailed in Windows Explorer. I've embedded the image into the file with Foobar2000 like I do with .jpgs but Windows Explorer still refuses to thumbnail them even with Icaros and all the other codec extensions I've tried. Android 13 thumbnails this exact file no problem so it must be a Windows thing. Is there any bugs in the code or reasons why Windows wouldn't be able to thumbnail WebP on .ogg files or HEIC, AVIF, JXL for that matter if Icaros is installed and supports the codec? If this isn't in Icaros's jurisdiction no problem, still just super confused why it isn't working. 

Thank you!

**Comment by Xanashi** [comment]
If you have OGG added in Icaros as a thumbnail filetype, then this is definitely an Icaros limitation.
Could you send me a sample or two? That would make it a lot easier for me to debug.

**Comment by 7eventech77** [comment]
Okay, uploaded them to the test repository

https://github.com/7eventech77/test-heic-images

**Comment by Xanashi** [comment]
Could you try this build, and see if that fixes the issue (same build as in #105):
https://www.mediafire.com/file/doaxfdutfc2l73u/Icaros_v3.3.3_b2_test3.zip/file

**Comment by 7eventech77** [comment]
> Could you try this build, and see if that fixes the issue (same build as in #105): https://www.mediafire.com/file/doaxfdutfc2l73u/Icaros_v3.3.3_b2_test3.zip/file

The issue with WebP is now fixed! Thank you sooo much! See below image. I tried with AVIF, HEIC, JXL embedded cover art encoded images but those still didn't work. Are you able to get these codecs to work or is it a crazy amount of work or not possible? If it is too much work then don't worry about it but if it is a quick fix then if you could go ahead and add those as a supported configuration that would be great. These codecs will become ever more widespread as time goes on and someone may want to use these for cover art. 

I tried to get Foobar2000 support to help me but they sorta acted like I was stupid with my question 🙃 Now time to bug VLC team about adding support to VLC android.
![WebP with opus](https://github.com/user-attachments/assets/c089c7ba-140a-486c-995e-757079ba73d4)

**Comment by Xanashi** [comment]
Embedded webp is fixed in [3.3.3 Beta 3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b3). 

Could you provide samples of files with embedded AVIF, HEIC cover art?
JXL is not currently supported in Icaros, although it will be at a later date.

**Comment by 7eventech77** [comment]
Awesome! I have uploaded an identical music track with the same image encoded in different file formats embedded as cover art. JPEG, WEBP, AVIF, HEIC, JXL. I know you said JXL isn't supported right now but I figured I would include it so you have it when you decide to implement for testing. Just let me know if you need anything else or have any questions!

Thank you!

https://github.com/7eventech77/Icaros-Test-Files

**Comment by Xanashi** [comment]
That's perfect. Thank you!
I'll make sure to check these out.

**Comment by Xanashi** [comment]
I've added support for AVIF, and HEIC as well in [v. 3.3.3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3).
I'll look into JXL at a later date as I still need to finish implementing JXL support in Icaros first.
I'm going to close this ticket for now, as most of it has been solved, if that's okay with you? 😉

**Comment by 7eventech77** [comment]
> I've added support for AVIF, and HEIC as well in [v. 3.3.3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3). I'll look into JXL at a later date as I still need to finish implementing JXL support in Icaros first. I'm going to close this ticket for now, as most of it has been solved, if that's okay with you? 😉

Thank you so much, both .avif and .heic thumbnailing for .ogg work correctly now! JXL isn't a big deal right now since the major browsers and operating systems don't support it currently but should hopefully in the future. Mainly just a nice to have at the moment.

**Comment by jdev2000** [comment]
I have the same problem with .opus extension
