### ISSUE TITLE
djvu support

### ISSUE THREAD

**Issue by 03302024** [Xanashi/Icaros#113]
I added djvu file format to the list, but no thmbnails show. Can you please add support for that as well?

**Comment by Xanashi** [comment]
I took a look at the format, and it would require additional libraries added to Icaros to support, 
so I don't plan to support it for the time being. 

I recommend you get a dedicated shell extension for DJVU thumbnailing:
https://www.google.com/search?q=djvu+shell+extension+pack

**Comment by 03302024** [comment]
it's a pity. Thanks for the link. Couldn't download from the link below, though.
https://www.epapyrus.jp/en/downloads/download?pid=5

**Comment by Xanashi** [comment]
You're right, the download doesn't work here either. 
Maybe try to contact them? I haven't tried that extension myself, I just saw it mentioned in another github discussion about djvu thumbnailing support. I'm not sure how legit it is.

**Comment by 03302024** [comment]
OK, Thanks for the info.
