### ISSUE TITLE
No thumbnails created in case of "VPS 0 / SPS 0 does not exist" info

### ISSUE THREAD

**Issue by Dean-Corso** [Xanashi/Icaros#115]
Hi,

I just would like to report a problem in case of dealing with video files (hevc) who having that VPS / SPS issues. In that case no thumbnail gets created in Windows Explorer. That's somehow bad of course. When I check the videos with ffmpeg CLI then it does print that info's first.
```
[hevc @ 0000026b1a701980] VPS 0 does not exist
[hevc @ 0000026b1a701980] SPS 0 does not exist.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '...(x265)_video.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf61.1.100
  Duration: 00:00:10.01, start: 0.000000, bitrate: 4559 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hvc1 / 0x31637668), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 4234 kb/s, 29.97 fps, 29.97 tbr, 90k tbn (default)
      Metadata:
        handler_name    : VideoHandler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 317 kb/s (default)
      Metadata:
        handler_name    : Stereo
        vendor_id       : [0][0][0][0]
At least one output file must be specified
```
So I'm using latest ffmpeg 7.0.2 build and it can create a thumbnail of that files too and the question why does Icaros can't do it with those files? Normal basic command to create an png text image of the video "-vframes 1 -vf scale=290:-1" and there it is. 

In my Windows (10 x64) Explorer and other tools using Windows thumbnails they all showing blank / VLC icon for those specific HEVC (with VPS / SPS 0 issue) only. Would like to ask whether you could check and fix that problem so that Icaros can also create thumbnails for those video files too. When I re-encode few seconds of the video with same HEVC codec libx265 then the VPS / SPS info's are gone and Icaros does create the thumbnail now. I don't wanna re-encode those videos new just because Icaros does not create thumbs at the moment for them you know. Would be nice if you could check out that problem and make Icaros working with them too. Thank You.

**Comment by Xanashi** [comment]
Hi Dean-Corso,

Would it be possible for you to share a sample file, where is issue is present?

**Comment by Dean-Corso** [comment]
Hello @Xanashi, 

just have a look in this topic https://github.com/stashapp/stash/issues/4124 so there you can find a example video what has same problem and Icaros isn't creating any preview image for that too. Here the [test.mp4](https://github.com/stashapp/stash/issues/4124#issuecomment-1720057183) video so just download it and then you will see it. So I hope that you can fix the problem Xanashi.

**Comment by Dean-Corso** [comment]
@Xanashi,

are you there and did you test the video now?

**Comment by Xanashi** [comment]
Hi Dean-Corso,
Sorry for the late reply. 
I got your samples and I've found a fix that will be included in the upcoming Icaros release.

**Comment by Dean-Corso** [comment]
Hello again @Xanashi,

sounds good that you found the problem and fixed it. Just wanna ask you whether you could release this fixed version already (pre-release) so that I and others don't need to wait anymore so long? So I just need that fix only to get all videos (hevc) I have displaying as thumbnails too. Would be nice if you could do that for me & all others who waiting for that hevc fix. 😃 Thank you.

**Comment by Xanashi** [comment]
Hi Dean-Corso,

Sorry for taking so long to release this fix, but it's finally here in [3.3.3 Beta 3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b3)
Let me know how it works.

**Comment by Dean-Corso** [comment]
Hello @Xanashi,

thank you very much for the latest beta release with HEVC thumbnailing fix. Seems to work now pretty good to create thumbs for all those HEVC files I have. Well done Xanashi. 😃

**Comment by Xanashi** [comment]
Thank you for the feedback. Glad to hear everything works now! 👍
