### ISSUE TITLE
Movie reel display on landscape OpenEXR files

### ISSUE THREAD

**Issue by fmnijk** [Xanashi/Icaros#118]
Hi
Square images display correctly. However, landscape OpenEXR images display movie reels. (the images are 16:9 in my test)
Thank you.
<img width="839" alt="Snipaste_2024-08-14_21-26-21" src="https://github.com/user-attachments/assets/71dd2088-deec-4e9b-8333-c0028c728360">

**Comment by Xanashi** [comment]
I'll make sure to fix this in the upcoming release of Icaros.

**Comment by Xanashi** [comment]
Fixed in [3.3.3 Beta 3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b3).
Give it a try.
