### ISSUE TITLE
Feature Request: Support the Oracle Outside In Viewer Tech

### ISSUE THREAD

**Issue by pa-0** [Xanashi/Icaros#120]
This is a library that is available for download from Oracle that supports over 400 formats.  (The uLister plugin for Total Commander consumes this dll)

**Comment by Xanashi** [comment]
There are several reasons why this library doesn't quite fit with Icaros' design and objectives, so this won't happen.
I appreciate the suggestion nonetheless, as I didn't know about this library.

**Comment by pa-0** [comment]
Sure.  FYI, the ulister plugin (which leverages the Oracle library) is in the wlx format, and there is a a project on here that supports wlx-type plugins to extend Windows' native file explorer.  (In case you or anyone who reads this issue wants to give it a try, you can find the repository here [Wlx2Explorer](https://github.com/AlexanderPro/Wlx2Explorer).

>[!Note]
>I have not personally tested this tool yet though I intend to, but judging by the state of the repository, responsiveness of the author to issues, I do believe it is maintained / in a working state.
