### ISSUE TITLE
Incorrect export and import of some settings

### ISSUE THREAD

**Issue by 03302024** [Xanashi/Icaros#121]
Settings like "Display movie reel on video thumbnails" and "Display icon overlay on thumbnails", don't get exported and imported correctly.

**Comment by clsid2** [comment]
Those are actually settings in Windows, and not specific to or dependent of Icaros.

**Comment by Xanashi** [comment]
clsid2 is correct. 
These settings are not directly related to Icaros, so I decided not include them in the export and import of settings. 
I'm open to change this, but it's not a priority at this time.

**Comment by 03302024** [comment]
My vote would be to also include those settings in export/import of settings, as it is confusing now.

**Comment by Xanashi** [comment]
Noted
