### ISSUE TITLE
Thumbnails are not working for symbolic links for files

### ISSUE THREAD

**Issue by JP95Git** [Xanashi/Icaros#122]
I use symbolic links organize my videos.

Working:
- Thumbnail for files
- Thumbnail for folder
- Thumbnail for symbolic link to folder

Not working:
- Thumbnail for symbolic link to file

See example:
![icaros](https://github.com/user-attachments/assets/3ecc03c0-f946-4447-9298-752c3a7118a3)

I tested it with Icaros v.3.3.3 Beta 2 and Windows 10 22H2.

Symbolic links are created using these commands:
`mklink /d folder-link folder`
`mklink file-link.avi file.avi`

As a workaround I use IrfanView Thumbnails to browse my files and folders because IrfanView shows all thumbnails. But I would love to see thumbnails in Windows-Explorer.

Possible related: #22

**Comment by Xanashi** [comment]
Thank you for the report. I've only ever tested symbolic links to folders.
I'll investigate it, but I have a sneaking suspicion this is a File Explorer issue, as it doesn't seem to work with Windows own native 
thumbnail provider either. At least in my initial tests.

**Comment by clsid2** [comment]
Afaik this is a Windows issue/limitation since Win8 due to tightened Windows security policies.

**Comment by JP95Git** [comment]
Thanks, you are right. I found an virtual machine running Windows 7 and tested a little bit:
- Windows 10 + Icaros: Thumbnails work only for files and folders, not for symbolic links
- Windows 7 without Icaros: Thumbnails work for files, folders and for symbolic links
- Windows 7 + Icaros: Thumbnails work for files, folders and for symbolic links

See screenshot for a visual result:
![thumbnail+link](https://github.com/user-attachments/assets/3660d4f7-4f2c-4a5a-8864-a489fe3f7ee9)

I think we can close this and probably #22 because Icaros works fine. It seems to be an Windows issue.

**Comment by Xanashi** [comment]
Thank @clsid2, that's very nice to know.

And thank you for testing @JP95Git. Good to get it confirmed. 
I believe you last point should have said "works for files, folders and symbolic links" right? 

I do wonder what the vulnerability is with symbolic linked files.

**Comment by JP95Git** [comment]
@Xanashi
Thanks, you are right. It was just a typo. I edited my comment.

**Comment by Xiarno** [comment]
> Thanks, you are right. I found an virtual machine running Windows 7 and tested a little bit:
> 
> * Windows 10 + Icaros: Thumbnails work only for files and folders, not for symbolic links
> * Windows 7 without Icaros: Thumbnails work for files, folders and for symbolic links
> * Windows 7 + Icaros: Thumbnails work for files, folders and for symbolic links
> 
> See screenshot for a visual result: ![thumbnail+link](https://private-user-images.githubusercontent.com/78929417/365993984-3660d4f7-4f2c-4a5a-8864-a489fe3f7ee9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyODQ0OTgsIm5iZiI6MTczNDI4NDE5OCwicGF0aCI6Ii83ODkyOTQxNy8zNjU5OTM5ODQtMzY2MGQ0ZjctNGYyYy00YTVhLTg4NjQtYTQ4OWZlM2Y3ZWU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE1VDE3MzYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNTRjODI0M2NjYWJmNDZjZDQ4ZWQxYThlYzI3MmUwOGQ5MWY4MGIxMDYzOThhYjQzNmQyZjdkZDcxYTIyMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PQ_TjAggp01nxD65HtnHu39B-6BHk1OLtDWUIWFkfcc)
> 
> I think we can close this and probably #22 because Icaros works fine. It seems to be an Windows issue.

By curiosity since this is a window issue, would you know any possible fix for it?

**Comment by JP95Git** [comment]
@Xiarno 

There are several "fixes" available:
- Don't use Windows. Linux has symbolic links too (but they are not the same as in Windows) and thumbnails always work in Linux.
- Use Windows 7, not a good idea.
- Contact Microsoft such they can fix this.
- Use another file manager instead of Windows Explorer. This seems like the best way, because Windows Explorer is getting worse with each new Windows. Unfortunately I didn't had time to find a good replacement.

**Comment by Xiarno** [comment]
> @Xiarno
> 
> There are several "fixes" available:
> 
> * Don't use Windows. Linux has symbolic links too (but they are not the same as in Windows) and thumbnails always work in Linux.
> * Use Windows 7, not a good idea.
> * Contact Microsoft such they can fix this.
> * Use another file manager instead of Windows Explorer. This seems like the best way, because Windows Explorer is getting worse with each new Windows. Unfortunately I didn't had time to find a good replacement.

I'd love to use Linux, but one of the program that I use *every single day*, so much so that it's a deal breaker to not have it, is not on Linux and after a year or two of searching & trying, I have not found a suitable replacement. If you are wondering, the program is ShareX.

Windows 7, yeah indeed not a good idea ahah.

For another file manager, after searching a bit I found OneCommander. Seems good.
