### ISSUE TITLE
MKV tags created with MP3tag are not showing in explorer with large files

### ISSUE THREAD

**Issue by Davey-101** [Xanashi/Icaros#123]
This may or may not be related to this issue:
https://github.com/Xanashi/Icaros/issues/56

The problem only occurs with MKV files larger than 4GB - the Title and Year tags I've added are not visible in explorer. I'm using version 3.3.2 on Windows 11 Home 23H2 and NTFS drives.

Tags appear correctly for mp4 of all sizes
Tags appear correctly for MKV smaller than 4GB.

What might be causing this?

**Comment by Davey-101** [comment]
I've updated to v3.3.3 b2 and it's fixed! Thanks!

**Comment by Xanashi** [comment]
You're very welcome! Thank you for taking the time to report potential issues!
