### ISSUE TITLE
Some videos are without length

### ISSUE THREAD

**Issue by oleedd** [Xanashi/Icaros#124]
System: Windows 7.
For example: [Nature.zip](https://github.com/user-attachments/files/16923267/Nature.zip)
Why?

**Comment by oleedd** [comment]
Already works.

**Comment by Xanashi** [comment]
Always great to hear. ^__^
I assume you upgraded to the latest beta? or was it just glitch in File Explorer?

**Comment by oleedd** [comment]
I just didn't enable properties.
But now I have a much bigger problem. 
I updated to the beta. And also updated K-Lite. And the system thumbnails stopped to work for .mp4 and .avi. I need system thumbnails as well. They stopped to work not right after updating. As I remember, it was after testing how Icaros works. But I am not sure, it may be after doing something with K-Lite.
But they work for .mov, .m4v, and if to rename .mp4 to .mov, a thumbnail appears. Reinstalling/deleting K-Lite does nothing. I tried like anything to fix.
Maybe you can suggest something? You are an expert in this, but I know quite little.

**Comment by oleedd** [comment]
I just didn't enable properties.
But now I have a much bigger problem.
I updated to the beta. And also updated K-Lite. And the system thumbnails stopped to work for .mp4 and .avi. I need system thumbnails as well. They stopped to work not right after updating. As I remember, it was after testing how Icaros works. But I am not sure, it could be after doing something with K-Lite (already tried all settings in it to fix).
But they work for .mov, .m4v, and if to rename .mp4 to .mov, a thumbnail appears. Reinstalling/deleting K-Lite does nothing. I tried like anything to fix.
Maybe you can suggest something? You are an expert in this, but I know quite little.

**Comment by oleedd** [comment]
@Xanashi
The problem is only with file extensions I entered in Icaros. I didn't enter .mov and .m4v, and they work. I need to fix at least .mp4.
