### ISSUE TITLE
ZIP and 7z thumbnails are displayed, but RAR thumbnails are not. Is RAR not supported?

### ISSUE THREAD

**Issue by wooeorbs** [Xanashi/Icaros#128]
I used an translator, so please forgive any mistakes.

**Comment by Xanashi** [comment]
The translator worked perfectly. 

RAR is supported, but your files may be compressed with RAR5, which is [currently not supported](https://github.com/selmf/unarr/issues/3).
Try using your decompression software to determine the format. You could also try and recompress your files,
and select anything besides RAR5 as the compression algorithm.

**Comment by wooeorbs** [comment]
I was unsure whether RAR thumbnails were supported because searching the README didn’t provide a clear answer. After seeing a response, I searched the Issues section and found the information at the very bottom. It’s a pity that RAR5 thumbnails are not supported. I hope the licensing issue can be resolved soon.

**Comment by Xanashi** [comment]
Yeah, it would be great to have RAR5 support in Icaros, but the proprietary license of the format makes it very annoying for 
developers to work with.

I should probably create a list in the readme of all filetypes that is known to work with Icaros. 🤔
