### ISSUE TITLE
Properties setting and .MOV

### ISSUE THREAD

**Issue by HHH0003** [Xanashi/Icaros#129]
Windows 23H2/24H2 is a train wreck!  They’ve destroyed the file Explorer .MOV file thumbnails and no longer work for some files… some do work properly. The Photo App is missing GPS data on some files.  ICAROS fixes the thumbnail issue with ease… properties is another issue. It works and will add the missing GPS data, but also changes the media created date tab by adding 1 hour causing chaos with photo order.  The .MOV file in the Photo App is unaffected time wise, just the properties tab… which changes the order which the Image is displayed in file explorer.  
Hopefully a fix can be found.

**Comment by Xanashi** [comment]
I'm very glad to hear Icaros is helping out with Explorer issues. 
The wrong dates definitely sounds like a bug. Could you provide a sample file?
I'll see if I can get a fix in before the next release.

**Comment by HHH0003** [comment]
> I'm very glad to hear Icaros is helping out with Explorer issues. The wrong dates definitely sounds like a bug. Could you provide a sample file? I'll see if I can get a fix in before the next release.

### I certainly can provide that for you...
_The thumbnails for .MOV files on the desktop or elsewhere on the computer vanished around the end of July this year. However, within the OneDrive folder, the thumbnails remained visible. Since iOS 18, .MOV files have ceased displaying GPS data or properties. Meanwhile, non-QuickTime files display correctly throughout the computer._

**This screenshot shows a folder on the desktop with ICAROS not installed..** 

![Screenshot 2024-10-07 154502](https://github.com/user-attachments/assets/08dbdba8-1176-41ff-b3f4-08de2937475e)

**This is the Explorer Gallery View without ICAROS installed, where the .MOV video time is not displayed.**  

![Screenshot 2024-10-07 160101](https://github.com/user-attachments/assets/46f93fd4-655f-4d23-bcca-c47b9b0a9adc)

****With ICAROS installed and its properties enabled, the New Photo App shows the GPS Information, but the image time is incorrect by one hour; it should display 3:04 PM. Prior to installing ICAROS, the GPS information was absent.**

![Screenshot 2024-10-07 160535](https://github.com/user-attachments/assets/68ab6362-9129-4e34-bf45-c6617f03c441)

**The Property tab of the file displays the incorrect time of 4:04 PM instead of the correct time of 3:04 PM.**

![Screenshot 2024-10-07 160856](https://github.com/user-attachments/assets/d1e92ac8-da35-426a-b189-5a338f63870f)

**The folder on the desktop where ICAROS is installed now displays thumbnails..**  

![Screenshot 2024-10-07 163412](https://github.com/user-attachments/assets/f96c6585-de63-460c-8f8f-3ce5ee1c8ad2)

**Comment by Xanashi** [comment]
Thank you for the info.
Could you send me one of the files where the date is wrong in Explorer/Photos?

**Comment by HHH0003** [comment]
**I needed to compress the file into a Zip format because when I attempted to upload the .MOV image, I received a message stating, "We don’t support that file type."**  

[20241007_190404000_iOS.zip](https://github.com/user-attachments/files/17285182/20241007_190404000_iOS.zip)

**Comment by Xanashi** [comment]
Thank you! I'll see what I can do, and get back to you.

**Comment by Xanashi** [comment]
Fixed in [3.3.3 Beta 3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b3). 
Give it a try.

**Comment by HHH0003** [comment]
> Fixed in [3.3.3 Beta 3](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b3). Give it a try.

Everything is functioning perfectly as expected.  Thank You!!!
