### ISSUE TITLE
hi10p / hi444p videos without thumbnail

### ISSUE THREAD

**Issue by masterd3** [Xanashi/Icaros#15]
Hi, all my videos mkv in hi444p and codec x265 looks like a green screen in thumnail.
I'm using version 3.2.0 beta 1 and windows 10 2004

**Comment by masterd3** [comment]
![Captura](https://user-images.githubusercontent.com/70135171/91022082-abfb2300-e5c2-11ea-9f7b-b10579101556.PNG)

**Comment by Xanashi** [comment]
Hi masterd3,

Any chance you could send me a sample file that exhibits this behavior?

**Comment by masterd3** [comment]
> Hi masterd3,
> 
> Any chance you could send me a sample file that exhibits this behavior?

Of course, i don´t know if any private way is possible (because copyright), but i'll let you a link where i downloaded 
https://drive.google.com/file/d/1EvXYtvn9iib53LZswPCb_qks7y1pVxqU/view?usp=sharing

**Comment by Xanashi** [comment]
The file seems to have playback issues in both FFplay, MPC-HC and VLC. 
It may have to be fixed in FFmpeg.
What player are you watching these files with?

**Comment by masterd3** [comment]
Hi again, i'm using potplayer, but I can play in mpc-hc too with LAV filter without any trouble

**Comment by garoto** [comment]
I recalled have seen these broken x264 renders before, so I went searching in the mpv issue tracker and found these:

https://trac.ffmpeg.org/ticket/6717
https://github.com/mpv-player/mpv/issues/4559
https://github.com/mpv-player/mpv/issues/4807

From what I gathered, seems to be that some revisions of x264 (<= 150?) would generate broken yuv444p10 files, but the people who generate these files have an habit to rip off the SEI from the video output, making impossible for ffmpeg (and libavcodec) to detect and apply its built-in workaround for those buggy x264 revisions.

In the ffmpeg ticket linked above, another possible (but kinda troublesome) workaround was posted by a dev. I tested it and it works.

**Comment by masterd3** [comment]
Thanks gareto for your reply.... i tried that solution of ffmpeg forum and you are right, it works fine. About LAV filters, i have last version 0.74.1 and that issue only happen in thumbnail, when i play the file i don't have any trouble. I have a lot of videos and that green thumbnail only happen in some series, that the reason  i opened this ticket, because were a weird situation for me (i don't have a lot knowledge about encode).

**Comment by Xanashi** [comment]
Thanks to all the info and help you've all given me, this issues should be fixed in the final version of Icaros 3.2.0.
