### ISSUE TITLE
auto-populate

### ISSUE THREAD

**Issue by horusra** [Xanashi/Icaros#16]
Right now the functionality for building thumbnails is that only the files currently visible in windows explorer get their thumbnails built, and then icaros stops until you scroll and new files come up to start generating thumbnails again.

Can there please be an option that makes Icaros first generate thumbnails of the files visible on list like it already does, but instead of stopping thumbnail generation, Icaros would continue building thumbnails of every other file in that same open folder without having to scroll to every file, wait, and then scroll again

**Comment by Xanashi** [comment]
Hi Horusra,

Unfortunately this is controlled and decided by Microsoft, and can't be changed by the shell extension. 
The lazy loading of thumbnails is the default (and afaik only) behavior of File Explorer.

The alternative is to use methods like [WinThumbsPreloader](https://github.com/bruhov/WinThumbsPreloader/), or a third party
file explorer to make the thumbnails load or preload all at once.
