### ISSUE TITLE
Windows thumbnails offset

### ISSUE THREAD

**Issue by oleedd** [Xanashi/Icaros#19]
Can you allow Windows Explorer to choose the offset position? It means the standard offset as a result of assigning some video player to a file format.

**Comment by Xanashi** [comment]
Hi oleedd,

Could you elaborate a bit, I'm not sure I understand what you're asking.

Kind regards,
Xanashi

**Comment by oleedd** [comment]
I use VLC which is assigned to video formats. But it doesn't display thumbnails for many video files. With Icaros, all videos are with thumbnails, but another pics are used for files which worked before. But I recognize videos by pics of the old offset - I used to it and want to keep it. But the standard Windows offset is changed in Icaros and similar programs. And I don't know the standard Windows offset value to set it manually.

**Comment by Xanashi** [comment]
Unfortunately, I'm not entirely sure how Windows determines its thumbnail offset for each file.
It's typically very early in the file, between 0 and 5% in, but as far as I can tell it's not a static value. 
Perhaps you can get similar thumbnails if you set Icaros to an early percentage offset like that. 
I wish I could provide you with a better solution.
