### ISSUE TITLE
Cache errors

### ISSUE THREAD

**Issue by BrainDedd** [Xanashi/Icaros#2]
As per my previous posts on the forums:
* NaN when building cache from the GUI
* Crash completely when attempting to clear cache

Setting the cache to dynamic does appear to fill it when browsing files though.

OS: Windows 10 Pro x64 15063.540
Version: 3.0.3 Beta 1

**Comment by Xanashi** [comment]
BrainDedd,
Thank you for being so patient with me. I still have your reports filed on my system.
Some inquiries:

- At what point does the GUI return NaN? Immediately?
- Before you click clear cache, and it crashes, would it be possible for you to zip up and send me
the cache files in your cache directory?

**Comment by oasuke** [comment]
I'm getting the same exact problem.
> At what point does the GUI return NaN? Immediately?
Yes.
Status:Indexing Completed Successfully [Took:4ms]

>Before you click clear cache, and it crashes, would it be possible for you to zip up and send me
the cache files in your cache directory?
I don't think it has anything to do what files are cached.  It gives me NaN % regardless of what directory I choose to rebuild with. 

OS: Windows 8.1 64bit
Version: 3.0.3 Beta 1*
Note: Isn't exclusive to this version.

**Comment by BrainDedd** [comment]
Happens immediately.
The cache folder is blank when this happens.

**Comment by Xanashi** [comment]
All good!
I'm reviewing the cache code atm. It sounds like this issue is happening while Icaros is scanning
your "included locations" for files to process.

Do any of you have drive paths (e.g. C:\) or very long folder names in your "included locations" in IcarosConfig on the cache page?

> The cache folder is blank when this happens.

IcarosConfig shouldn't give you the option to clear the cache if no cache files are present. Strange.

**Comment by BrainDedd** [comment]
There seem to be two issues here, but I'm not sure if they're related or not.
Firstly when I scan a location with the indexer I immediately get a NaN % complete reading.
Secondly I cannot clear the cache using the clear cache button (once files have been added by dynamic caching.)

Imgur album with repro images: [http://imgur.com/a/Zogam](http://imgur.com/a/Zogam)

**Comment by BrainDedd** [comment]
I see there's a lot more error handling in terms of setting permissions but it doesn't ever seem to actually succeed in setting what it needs. Dynamic cache builds just fine and the debug thumbnailing also runs fine on most of my files but building cache in the config still throws the same error.

**Comment by Xanashi** [comment]
Hi BrainDedd,
So I ran those tests, and I did find a bug, just not your bug. I still cannot figure out how to recreate this one.
I've fixed the bug I found, as well as a lot of small problems in the cache code in the latest release. 
Could you give it try, and see if bug still persists?

**Comment by Xanashi** [comment]
Hi BrainDedd,

I'm going to close this issue for now, but you're welcome to reopen it at any time if the bug still persists. 
The [latest beta](https://github.com/Xanashi/Icaros/releases/tag/v3.3.1b1) contains also contains some cache fixes, so be sure to give it a try if you still have the issue.
