### ISSUE TITLE
webp codec for Windows xp

### ISSUE THREAD

**Issue by antoxabond** [Xanashi/Icaros#21]
Can you adapt using your developments
"https://github.com/webmproject/webp-wic-codec" (using visual studio 2010)
for use on Windows xp.
Your library is very powerful and functional (and supports webp thumbnails) but takes up a lot of memory and computer resources. webp-wic-codec is small and lightweight, but not supported on Windows xsp.
(
I dare to assume that it would probably be easier for you to separate the project into the COM server library and the libwebp.dll from the "https://github.com/webmproject/libwebp" project. 
)

I would really like to have a webp codec for Windows xp.
Best regards, Anton.

**Comment by Xanashi** [comment]
Hi Anton,

I'm not sure how well supported WIC Codecs are on Windows XP, but if the project can be compiled without errors [using the v141_xp toolset](https://docs.microsoft.com/en-us/cpp/build/configuring-programs-for-windows-xp?view=msvc-160), 
there is a chance it may just work straight out of the box.

Unfortunately, I don't have the setup or Win XP machine or VM to compile and then test on, so it's a bit too much for me to 
dig into right now. Sorry!

I hope you can make it work though!

Kind regards,
Xanashi
