### ISSUE TITLE
[BUG] Recursive cache still not working (3.3.0 RC1)

### ISSUE THREAD

**Issue by Shituation** [Xanashi/Icaros#27]
![image](https://user-images.githubusercontent.com/43975882/197352528-faa8d8be-9dff-4ef0-94ce-c6f21efdfad4.png)

Configured the root of a drive full of folders with multimedia (no other stuff in it)
Configured filetypes:
`3g2;3gp;3gp2;3gpp;amv;asf;avi;bik;bmp;dds;divx;dpg;dv;dvr-ms;evo;f4v;flv;gif;hdmov;jpeg;jpg;k3g;m1v;m2t;m2ts;m2v;m4b;m4p;m4v;mk3d;mkv;mov;mp2v;mp4;mp4v;mpe;mpeg;mpg;mpv2;mpv4﻿﻿;mqv;mts;mxf;nsv;ogm;ogv;qt;ram;rm;rmvb;skm;swf;tiff;tp;tpr;trp;ts;vob;webm;webp;wm;wmv;xvid`

**Comment by Xanashi** [comment]
Hi Shituation,

Could you please try this test build and see if it helps:
https://www.mediafire.com/file/ji3skjlc7cal1q5/Icaros_v3.3.0_0x14_Test.zip/file

It contains some pathing logic, and a debug dialog that pops up if the 0x14 error is hit.

**Comment by Shituation** [comment]
Seems to be working now, no error this time 👌
It let me use the root of a drive as the starting point and it seems to recognize the folder structure now.

**Comment by Xanashi** [comment]
Thank you so much for testing Shituation! 
Really happy to hear it's working now for you.

I'll be sure to mark this as completed as soon as these changes have been released.

**Comment by Xanashi** [comment]
Fixed in #39

**Comment by Shituation** [comment]
Its giving the same error again on 3.3.1.
Something is wrong, it doesn't work with your posted "fixed" version above either.

Maybe a windows update causing this? 

~UPDATE: Tested a folder on my C drive (unencrypted) and it worked. The problem seems to be when files are encrypted using bitlocker.~

UPDATE 2: Nope, a single encrypted folder works, so I don't know why the recursive option doesn't work.

UPDATE 3: So here is what I've found: if a folder contains a file that is NOT in the "thumbnail filetypes" config, the whole folder is discarded; in my case TS files where not in that option, so I added it and the program suddenly recognized all the folders configured with the recursive option ticked.

**Comment by Xanashi** [comment]
Hi Shituation,

Thank you for bringing this to my attention! I'll make sure to look into it ASAP.

**Comment by Xanashi** [comment]
Hi Shituation,

I wasn't able to reproduce the issue you described above unfortunately. 
Could you try the latest release #63 
It contains a couple of Cache fixes, and there is a chance it may fixed a bug like this.

**Comment by Xanashi** [comment]
Closing this for now, don't hesitate to reopen if needed.

**Comment by Poilaucul** [comment]
Esalia?
