### ISSUE TITLE
Windows Defender Detects Portable v3.0.3 Beta 1 as Trojan:Win32/Azden.A!cl

### ISSUE THREAD

**Issue by Metaphorce812** [Xanashi/Icaros#3]
I downloaded the new portable version of Icaros today from your mediafire link: `http://www.mediafire.com/file/bpizw461xtb55o4/Icaros_v3.0.3_b1.zip`
But it was immediately deleted and Windows Defender (on Windows 10 Pro x64 v1703 Build 15063.540) reported it as "Trojan:Win32/Azden.A!cl" "Alert Level: Severe" (I've included a screenshot below).

I disabled Windows Defender so that I could actually download and unzip the file. I then uploaded "IcarosConfig.exe" to [VirusTotal and 1/64 engines (Sentinel One) detected it as "static engine - malicious"](https://www.virustotal.com/#/file/c2b0b8810a7d83a51ac73bca638acfcad26c047d9059dce096a217a204e84fef/detection).

However when I downloaded the installer, Windows Defender had no problems with it and 0/64 engines on VirusTotal detected anything. So the issue seems to only be with the portable version.

I've been using Icaros for years and I know you would never intentionally release an infected version, but there seems to be something causing a false positive. I hope you can figure it out and get it fixed soon. Thanks for this great program and keep up the good work.

![icaros_v3 0 3_b1_windefender_trojan_win32_azden a cl](https://user-images.githubusercontent.com/13408558/29336371-8eedc752-81db-11e7-90c3-05854b7e453f.jpg)

**Comment by Xanashi** [comment]
Hi Metaphorce,
Thank you for the prompt report. 
And that is honestly really strange. IcarosConfig is quite vanilla, except for a couple of calls to Windows registry when it registers the various extensions.

And for some reason my own Windows Defender didn't react. :/
I'll report it to MS right away and hopefully it'll be fixed soon.

**Comment by Xanashi** [comment]
I reported the false-positive to MS right after we last spoke, and send Icaros in for scanning.
MS confirmed the files were clean later the same day, so hopefully everything should be in order now. ;)
I'll close the issue for now, but be sure to let me know if the problem persist or comes back.
