### ISSUE TITLE
10 bit 4:4:4 chroma sub-sampled H.264 videos have gray thumbnails (3.0.3 Beta 1)

### ISSUE THREAD

**Issue by LazyBumHorse** [Xanashi/Icaros#4]
Mostly gray, sometimes there are some lines at the top as if the thumbnail generation was aborted. All other kind of encodings seem to work fine (10 bit 4:2:2, 4:2:0, all 8 bit).

**Comment by Xanashi** [comment]
Confirmed bug. 
I may have a possible fix ready, but still some further testing is required.

**Comment by Xanashi** [comment]
This should now be fixed in 3.0.3 beta 2. Give it a try. ;)

**Comment by LazyBumHorse** [comment]
Yep, looks good, I couldn't reproduce the issue with any file, nice work!

**Comment by Xanashi** [comment]
Thank you for testing. :)
