### ISSUE TITLE
Can you please open source Icaros?

### ISSUE THREAD

**Issue by DavidParks8** [Xanashi/Icaros#40]
I would love to be able to contribute, upgrade off of old .net versions, etc. Would you be willing to post the source code for others to contribute?

**Comment by Xanashi** [comment]
Hi David, 
Not at this point in time, but it will most likely be open sourced in the future. 
But please don't hesitate to post suggestions or feature request. I'm always open to new ideas.

The current .NET version is very deliberate. It is to allow the highest compatibility with most versions
of Windows, while also avoiding the installation of additional frameworks, during the installation of Icaros, on most systems. 

That said, the upcoming version of Icaros will upgrade .NET to 4.6.

**Comment by DavidParks8** [comment]
Have you considered upgrading to .net 7 and compiling to a self contained executable? This would work on all versions of windows and not require any extra framework installations, while also being much more secure and performant.

**Comment by Xanashi** [comment]
Hi David,
Just wanted to thank you for the suggestion. I've been looking into it, and I'm still weighing the options. 
One thing I wondering is if it's possible to create a single-file app that targets "Any CPU"?

**Comment by DavidParks8** [comment]
I do not believe it is possible to create a self-contained app that targets Any CPU, because Any CPU by definition requires a framework to be installed on the machine prior to running an executable.
