### ISSUE TITLE
[BUG] cover not displayed unless MIME type is "image/jpeg"

### ISSUE THREAD

**Issue by mjolnir870** [Xanashi/Icaros#42]
If an mkv has a cover attachment of type `image/webp` and `cover.webp`, Icaros doesn't use it for the thumbnail. If the MIME type is changed to `image/jpeg`, then Icaros correctly uses it as the cover. Can Icaros add support for covers with MIME types other than `image/jpeg`?

![image](https://user-images.githubusercontent.com/35158449/223679525-223a24fa-709e-464c-a66c-21fb09c48e4a.png)

In the zip are samples of a video with an embedded webp cover (MIME type `image/webp`), and then two copies, one with MIME type `image/jpeg` (correctly thumbnailed) and one with MIME type `image/jpg` (no thumbnail). The raw webp thumbnail is also included.

[samples.zip](https://github.com/Xanashi/Icaros/files/10919333/samples.zip)

**Comment by Xanashi** [comment]
Hi mjolnir870,

This is definitely a problem. I'll make sure it's fixed in the upcoming release.
Thank you for the samples! Really helps me fixing the issue much faster.

**Comment by mjolnir870** [comment]
> This is definitely a problem. I'll make sure it's fixed in the upcoming release. Thank you for the samples! Really helps me fixing the issue much faster.

Thanks in advance for the fix! I didn't think about it when making samples but `image/png` should probably be handled as well.

**Comment by Xanashi** [comment]
image/png should already be supported in the current version of Icaros 👍

**Comment by Xanashi** [comment]
Hi mjolnir870,

This should be fixed in the latest beta release. Please try it out!
[Find 3.3.1 Beta 1 HERE](https://github.com/Xanashi/Icaros/releases/tag/v3.3.1b1)
