### ISSUE TITLE
Drag and Drop Issue/Bug with HEIC and MP4 Files.

### ISSUE THREAD

**Issue by montajyan** [Xanashi/Icaros#44]
Hi, first thanks for such a nice and leight software :)
But i have found a bug or maybe an error. While i did drag and drop a "heic" and "mp4" file i did receive this error. I did add "mp4" manually, but still the error continues. Can you check it?

Tnanks in advance :)

![Screenshot 2023-03-19 130302](https://user-images.githubusercontent.com/119154016/226174114-f9bdab88-4a31-4b09-b72f-84ea08e3bb39.png)
![Screenshot 2023-03-19 130432](https://user-images.githubusercontent.com/119154016/226174165-72d1578e-5451-4b8e-9eb4-ae71f106100b.png)

**Comment by PlumErrand** [comment]
Hello, I am also experiencing this error. If I go back to the previous version I do not get the error. Also I tried your test build for this error in this thread: https://shark007.net/forum/Thread-Bug-Report-REl-3-3-0-Final, however all that does is remove the error message, but the thumbnails do not change. Thank you in advance for any insight.

Some additional information: 
Windows 11 Pro
Administrative account
Error occurs on local drive as well as external drives

**Comment by Xanashi** [comment]
Both bugs should be fixed in the latest beta release. Please give it a try!
[Find 3.3.1 Beta 1 HERE](https://github.com/Xanashi/Icaros/releases/tag/v3.3.1b1)

**Comment by PlumErrand** [comment]
Thank you, this fixes the problem! Much appreciated.
