### ISSUE TITLE
[Feature Request] Please add "m4v" extension to the video properties checkboxes

### ISSUE THREAD

**Issue by Hlsgs** [Xanashi/Icaros#46]
It is one of the two supported output extensions in `HandBrake`(the other being `mp4`), so I would imagine it's not that obscure.

And, as a bonus, it could be added to the default thumbnailing filetypes list.

**Comment by Xanashi** [comment]
Absolutely, it will be added in the upcoming version. 👍

**Comment by Xanashi** [comment]
This has added in #63
