### ISSUE TITLE
Is AV1 codec supported?

### ISSUE THREAD

**Issue by Klaus1189** [Xanashi/Icaros#48]
Maybe I am doing something wrong. Latest beta release is installed.

**Comment by Xanashi** [comment]
It should be supported. 
What container is the stream stored in? MP4, MKV...?
Have you tried dropping the file onto the Thumbnailing page of IcarosConfig?

**Comment by Klaus1189** [comment]
These are MKV files.
I had to install Microsoft AV1 Video Extension, then it worked. I just thought it supports it out of the box.

**Comment by Xanashi** [comment]
It does support it out of the box. The MS AV1 video extension is not needed. 
If possible (and if you're ok with it), could you send me one of the files that doesn't work?

**Comment by Klaus1189** [comment]
Of course, maybe I am doing something wrong. Please test this one, if I remember correctly it was one like this:
https://drive.google.com/file/d/1d6HNc0pKsJvaqePhTrYqP6JZYaBZsDtA/view?usp=sharing

**Comment by Xanashi** [comment]
Thank you!

I just tested it and the file worked fine with Icaros (see screenshots).

![AV1_Test](https://github.com/Xanashi/Icaros/assets/30978586/7cad7e7e-f7da-467b-b90b-30e80fbbf8bc)
![AV1_Thumbnail](https://github.com/Xanashi/Icaros/assets/30978586/ed04ecf3-c19d-468c-99f3-ace124a6fb88)

Make sure MKV is added in the filetypes on the Thumbnailing page of IcarosConfig.
Then try to Disable then Enable thumbnailing again, and see if that fixes it.

**Comment by Klaus1189** [comment]
Seems like I disabled accidentally thumbnailing in Icaros... Shame on me.

**Comment by Xanashi** [comment]
No worries, it happens. 👍 
I'm just glad it all works for you now.
