### ISSUE TITLE
[Bug?] Cbx with Avif image files don't have thumbnails

### ISSUE THREAD

**Issue by 5h4k3** [Xanashi/Icaros#50]
Given the young age of the Avif format, I didn't expect it to be supported until I saw AVIF thumbnailing has come with Icaros 3.3.0.

So supported or not, I thought it might be a bug, hence my report.

Cbz, Cb7 and Cbt so far, doesn't show a thumbnail if they are composed of Avif files.

Have a nice day!

**Comment by Xanashi** [comment]
Hi 5h4k3, 
I think it's just a case of me not anticipating AVIF files in CBZ, etc. and therefore the parser doesn't recognize the filetype.
Could you send me sample file? I'm quite sure I have a fix, just need to test it.

**Comment by 5h4k3** [comment]
Of course, here are two... The two CBZ are zipped to be uploaded.
[Anne Rice - The Mummy 12.zip](https://github.com/Xanashi/Icaros/files/11658543/Anne.Rice.-.The.Mummy.12.zip)
[Article de télérama.zip](https://github.com/Xanashi/Icaros/files/11658544/Article.de.telerama.zip)
 And thank you for everything!

**Comment by Xanashi** [comment]
Thank you for the sample files 5h4k3!
Glad I got them from you, because my fix needed a few adjustments to make it work properly, but now does. 
It will be fixed in the upcoming version of Icaros.

**Comment by Xanashi** [comment]
This has fixed in #63

**Comment by SergDawger** [comment]
Wasn't sure if I should create a new issue or just add onto this one, but the same is true if the first image in a CBx file is JPEG-XL, no thumbnail in Windows Explorer.
