### ISSUE TITLE
[Request] Option so that Thumbnails are based on Metadata tag/tags

### ISSUE THREAD

**Issue by SamRohod** [Xanashi/Icaros#55]
Hi,

Is it possible to add an option to force video thumbnails to be created based on some metadata values?
I'm thinking specifically of the "Rotation" tag. I have hundreds of videos that when played are correct but their video thumbnails have the wrong rotation.

I use K-Lite Codec Pack (Mega) and based on testing few videos with MediaInfo & [ExifTool](https://exiftool.org/), it seems that Media Player Classic uses the metadata to rotate the video when playing but the thumbnail creation (using Icaros) does not use the metadata to rotate thumbnails correctly.

Thank you.

**Comment by Xanashi** [comment]
Hi SamRohod,

Icaros does actually rotate thumbnails based on any "Rotation" tags. If you have files where this doesn't happen,
please send one my way, and I'll be sure to fix it.

**Comment by clsid2** [comment]
Clear the windows cache with cleanmgr.exe and reboot

**Comment by SamRohod** [comment]
I have attached two videos with this problem. One has rotation=90 and the Other rotation=180. I also attached a picture of how it looks on my computer.

I tried the Disk Cleanup tool (cleanmgr.exe) to clean the thumbnails but the problem remains.
Before posting this, I even tried installing K-Lite Codec Pack Mega (default settings) on a freshly installed Windows 11 with only Intel and Nvidia drivers installed by me, and I got the same result as in the picture attached.

[example.zip](https://github.com/Xanashi/Icaros/files/11853442/example.zip)

**Comment by Xanashi** [comment]
Thank you for the samples!

I took a look at the issue, and found the bug. Apparently the function that returns the rotation angle in FFmpeg, returns an incorrect value when compiled with the latest GCC. 

I'll make sure to fix the issue in the upcoming release of Icaros. 
Glad you caught this bug.

**Comment by Xanashi** [comment]
This has fixed in #63
