### ISSUE TITLE
MKV Titles edited with MP3Tag don't show when Icaros is enabled.

### ISSUE THREAD

**Issue by anthony75smith75** [Xanashi/Icaros#56]
MKV Titles edited with MP3Tag don't show in Windows Explorer when Icaros is Enabled. We could be quick to blame MP3Tag but the MP3Tag edited MKV Titles work perfectly in Windows Explorer when Icaros is disabled. Other programs like MKVToolnix and PropEdit seem to produce Titles that work with Icaros on or off. What is going on here? Have also lodged a support request with MP3Tag.

https://community.mp3tag.de/t/title-tag-in-mkv-files-not-shown-in-windows-explorer/61373/8

**Comment by anthony75smith75** [comment]
Ok have done some additional research and testing. Some programs like MKVToolNix and PropEdit will write a normal Title Tag. MP3Tag appears to only write Global MKV Tags. Very confusing. Windows Explorer without Icaros (Windows 11 22H2) will read both tag types but prefers global tags. Icaros will only read normal tags and ignores ALL global tags. We need some consistency here! Can we add global MKV tag support to Icaros?
![Icaros Off - Windows Prefers Global Titles](https://github.com/Xanashi/Icaros/assets/77678231/198ea02c-685f-485e-90be-ca074d95dee7)
![Icaros On - No Global Tag Support](https://github.com/Xanashi/Icaros/assets/77678231/cdb4c1c5-5178-49a5-a20d-3067c246fbc9)
![MKVToolNix - Extra Global Tags Created by MP3Tag](https://github.com/Xanashi/Icaros/assets/77678231/f7627a08-5f70-48ae-bcfb-01d32717fd6e)
![MKVToolNix - No Global Tag](https://github.com/Xanashi/Icaros/assets/77678231/48733704-4826-41ce-981d-e74611b4dc80)

**Comment by Xanashi** [comment]
Which version of Icaros are you currently using?

**Comment by anthony75smith75** [comment]
The latest. v3.30

**Comment by Xanashi** [comment]
Try the latest beta version 3.3.1 Beta 1. 
https://github.com/Xanashi/Icaros/releases/tag/v3.3.1b1
It comes with a very large amount of property fixes.

**Comment by anthony75smith75** [comment]
Just tested the Icaros 3.31 Beta1. Can confirm the Titles for MKV now work as they do in Windows 11 without Icaros installed. MKV Global tags have priority which is what MP3Tag writes. If there are no global tags then the normal tags are shown. If MKV has both normal and global then MP3Tag shows the newest and updates global tag when changed. Album, Album Artist, Genre, Year, Comments, Bitrate, Bitdepth, AudioTracks, VideoTracks and MANY MORE are working for MKV and FLAC files with Icaros 3.31 installed. Problem seems solved! Much thanks to all.

**Comment by anthony75smith75** [comment]
Just did Windows Update to Windows 11 22H2. I was on 21H2. Sorry for any confusion as I thought I was already up to date. 22H2 has broke Icaros again. I have disabled it to get the MKV Titles and other tags working in Explorer.

**Comment by Xanashi** [comment]
I just did fresh VM with Windows 11 22H2. Icaros worked as expected with all properties showing up correctly including the MKV/MKA titles (see screenshot).
Did you make sure to install the latest beta version of Icaros? 
You may also want to refresh Explorer after Enabling Icaros. You can do that on the Tools Page in IcarosConfig.

![properties_win11](https://github.com/Xanashi/Icaros/assets/30978586/0e2ac52f-ac6c-49e6-9a63-6a07a9a1a250)

**Comment by Xanashi** [comment]
I'm going to close this issue for now, since there haven't been any follow-up,
but don't hesitate to post a follow-up and get it reopened.
