### ISSUE TITLE
Installer - german translation

### ISSUE THREAD

**Issue by Klaus1189** [Xanashi/Icaros#57]
Hi,
I want to to translate the installer into german.
Please let me know what I need to do for it.

I translate already MPC-BE, MSI Afterbuner and Rivatuner Statistics Server. So I have some knowledge ;-)

**Comment by Xanashi** [comment]
Hi Klaus,

Thank you so much for considering helping with the translations! 

I've written a guide here:
https://github.com/Xanashi/Icaros/discussions/29

Just let me know if you have any questions about the process.

**Comment by Klaus1189** [comment]
OK, I take a look at it. Is german translation other than installer complete and maintained?

**Comment by Xanashi** [comment]
No the German translation is currently not up to date. It's been a few years since the last update to the translation.

**Comment by Klaus1189** [comment]
OK, I translate it also, but it will take some time. Can you post the old german file, so I can transfer old to new and add missing strings?

**Comment by Xanashi** [comment]
No problem, thank you so much for contributing! 
You can get the latest edition of the German translation directly from your Icaros installation. 
Look in the Icaros installation directory under \Resources\Localize, there is a file called Config.de.po, 
which you can just open in PoEdit and continue to work on.

**Comment by Klaus1189** [comment]
I opened a new thread for german translation:
https://github.com/Xanashi/Icaros/discussions/61

I will use this thread for updates :)

**Comment by Xanashi** [comment]
I've replied to your thread! Sorry for being slow!
