### ISSUE TITLE
Icon overlays on thumbnails doesn't work to .zip files

### ISSUE THREAD

**Issue by fortissimo247** [Xanashi/Icaros#58]
![Screenshot_302](https://github.com/Xanashi/Icaros/assets/125655800/12d68a0f-5953-468b-af1f-b77861ea6129)

It work nicely to .mp4 files but not to .zip
How do I fix it?

**Comment by Xanashi** [comment]
Icaros doesn't handle the icon overlays on thumbnails, it's handled by Windows. 
You could try to check in the Windows Registry, if the following value exists:

[HKEY_CLASSES_ROOT\\SystemFileAssociations\\.zip]
"IconOverlay"

If the IconOverlay value exists, you need to delete it to make icon overlays appear on ZIP files.

**Comment by fortissimo247** [comment]
![Screenshot_304](https://github.com/Xanashi/Icaros/assets/125655800/4ecdca6c-2a17-4fd1-b487-ffe73474d33b)
![Screenshot_303](https://github.com/Xanashi/Icaros/assets/125655800/18016652-c857-4353-83df-c8f7d3a50843)

I thought Icaros can handle icon overlay because that option exists, and it works well to .mp4 files.





![Screenshot_305](https://github.com/Xanashi/Icaros/assets/125655800/ac6ae6ed-e857-4834-9aad-9ed6d2823ba2)
And I couldn't find "IconOverlay" in my registry.

**Comment by Xanashi** [comment]
It's just a shortcut to the following folder option:

![iconoverlay_folderoptions](https://github.com/Xanashi/Icaros/assets/30978586/b125701d-a174-4647-90a5-4150060aa79d)

Check the following key for the IconOverlay value

[HKEY_CLASSES_ROOT\\.zip]

Also check the 'Content Type' value in that key. If it for example says 'image' before the front slash,
you could try to look for the IconOverlay value in the following key:

[HKEY_CLASSES_ROOT\\SystemFileAssociations\\image]

**Comment by fortissimo247** [comment]
I still can not find that keys, but I reconized it work on .7z files.
I used CBX Shell that program showing thumbnail of .zip or .rar files before using Icaros. Could that be the problem?

And thank you very much answering me.

![Screenshot_309](https://github.com/Xanashi/Icaros/assets/125655800/ec8ea8c3-c3e9-4ad1-887d-3aeeb8853b86)

**Comment by Xanashi** [comment]
It is almost certainly a registry setting that is set wrong. Any software interacting with zip files could have caused this.
I personally don't use Icaros on zip files, so I haven't tested this scenario all that much. 

What is the "Content Type" of .zip in your registry?
(Found under [HKEY_CLASSES_ROOT\\.zip])

**Comment by fortissimo247** [comment]
Oh I was finding at wrong directory, and now I found it.

![Screenshot_310](https://github.com/Xanashi/Icaros/assets/125655800/17072bd4-1af7-4683-a397-1af78680a4b6)
![Screenshot_311](https://github.com/Xanashi/Icaros/assets/125655800/e229bf34-8c2b-4abb-8265-3edeb0241a84)
![Screenshot_312](https://github.com/Xanashi/Icaros/assets/125655800/bd0e0b6e-b258-4338-a525-134c1da8e690)
![Screenshot_313](https://github.com/Xanashi/Icaros/assets/125655800/17c2db3a-7e73-4514-86f7-770d1b06f5b1)

**Comment by Xanashi** [comment]
Hmm... it may be the PerceivedType you need to look for in the SystemFileAssociations. 
So try looking for compressed and see if that has a TypeOverlay value. 

As you can see in your SystemFileAssociations\\image key, the TypeOverlay value should block overlay icons on any image formats.

**Comment by fortissimo247** [comment]
After several attempts, I solved by removing below key.
HKEY_CLASSES_ROOT\SystemFileAssociations\.zip\CLSID

Thank you for helping!!

**Comment by Xanashi** [comment]
Interesting. I didn't know that could affect the icon overlays.
Thank you for posting your solution! 
I'm sure it will be helpful to others with similar issues.
