### ISSUE TITLE
Creating Thumbnails for Zip Files

### ISSUE THREAD

**Issue by AsianKR** [Xanashi/Icaros#59]
Hey,

so how exactly do I create thumbnails for ZIP-Files? Do I just have to put an image into the ZIP-File? Cause that doesnt seem to work for me...

Sorry, if this is a obvious question. Im kinda clueless, about how this works.

Thanks in regards.
![Unbenannt](https://github.com/Xanashi/Icaros/assets/79062644/5e2d056a-0975-4631-9812-d4c8b27baef4)

**Comment by Xanashi** [comment]
Hi AsianKr,
Did you find the solution to your problem?

**Comment by AsianKR** [comment]
Hey,

yes, I noticed that I already had CDisplayEx installed. Removing it fixed the problem.

**Comment by Xanashi** [comment]
Thank you so much for providing the solution to your problem, hopefully it will help other users with the same issue.
