### ISSUE TITLE
IcarosConfig.exe crash after Systemrecovery

### ISSUE THREAD

**Issue by Qoolize** [Xanashi/Icaros#60]
Hello! 

Icaros is crashing after start with no realy reason. I have tried ReInstall, clear all Data. Nothing. 
I must use a Systemrecovery. After this, program will no longer work. 
.NET Framework, Runtime etc. is all new.

- Win. 7 x64

**Comment by Xanashi** [comment]
Hi Qoolize,

This sounds very strange. Have you checked the event log for any error messages?
Does Icaros show any error messages?

**Comment by Qoolize** [comment]
Hello!

Sorry for the late answer, I had a lot of problems with my PC... 
Nope its Crash normal, without Error-Message.
Anyway, i got crash info from a data recovery:

Version=1
EventType=APPCRASH
EventTime=133340920745627281
ReportType=2
Consent=1
ReportIdentifier=a4b40c07-24cf-11ee-82b6-5404a61515bf
IntegratorReportIdentifier=a4b40c06-24cf-11ee-82b6-5404a61515bf
Response.type=4
Sig[0].Name=Anwendungsname
Sig[0].Value=IcarosConfig.exe
Sig[1].Name=Anwendungsversion
Sig[1].Value=3.3.0.301
Sig[2].Name=Anwendungszeitstempel
Sig[2].Value=643293fc
Sig[3].Name=Fehlermodulname
Sig[3].Value=KERNELBASE.dll
Sig[4].Name=Fehlermodulversion
Sig[4].Value=6.1.7601.24384
Sig[5].Name=Fehlermodulzeitstempel
Sig[5].Value=5c6e248c
Sig[6].Name=Ausnahmecode
Sig[6].Value=c06d007e
Sig[7].Name=Ausnahmeoffset
Sig[7].Value=000000000000be0d
DynamicSig[1].Name=Betriebsystemversion
DynamicSig[1].Value=6.1.7601.2.1.0.256.1
DynamicSig[2].Name=Gebietsschema-ID
DynamicSig[2].Value=1031
DynamicSig[22].Name=Zusatzinformation 1
DynamicSig[22].Value=7283
DynamicSig[23].Name=Zusatzinformation 2
DynamicSig[23].Value=72836eb6216b49be15302fdb224c1b5d
DynamicSig[24].Name=Zusatzinformation 3
DynamicSig[24].Value=94a9
DynamicSig[25].Name=Zusatzinformation 4
DynamicSig[25].Value=94a9dbf302a49ef82c9937e7727de826
UI[2]=C:\Program Files\Icaros\IcarosConfig.exe
UI[3]=IcarosConfig funktioniert nicht mehr
UI[4]=Windows kann online nach einer Lösung für das Problem suchen.
UI[5]=Online nach einer Lösung suchen und das Programm schließen
UI[6]=Später online nach einer Lösung suchen und das Programm schließen
UI[7]=Programm schließen
LoadedModule[0]=C:\Program Files\Icaros\IcarosConfig.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\Windows\system32\KERNEL32.dll
LoadedModule[4]=C:\Windows\system32\KERNELBASE.dll
LoadedModule[5]=C:\Windows\system32\ADVAPI32.dll
LoadedModule[6]=C:\Windows\system32\msvcrt.dll
LoadedModule[7]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[8]=C:\Windows\system32\RPCRT4.dll
LoadedModule[9]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
LoadedModule[10]=C:\Windows\system32\api-ms-win-core-synch-l1-2-0.DLL
LoadedModule[11]=C:\Windows\system32\SHLWAPI.dll
LoadedModule[12]=C:\Windows\system32\GDI32.dll
LoadedModule[13]=C:\Windows\system32\USER32.dll
LoadedModule[14]=C:\Windows\system32\LPK.dll
LoadedModule[15]=C:\Windows\system32\USP10.dll
LoadedModule[16]=C:\Windows\system32\IMM32.DLL
LoadedModule[17]=C:\Windows\system32\MSCTF.dll
LoadedModule[18]=C:\Windows\system32\VERSION.dll
LoadedModule[19]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
LoadedModule[20]=C:\Windows\system32\VCRUNTIME140_CLR0400.dll
LoadedModule[21]=C:\Windows\system32\ucrtbase_clr0400.dll
LoadedModule[22]=C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\3597805b7d7dce423abb491985dd28e8\mscorlib.ni.dll
LoadedModule[23]=C:\Windows\system32\ole32.dll
LoadedModule[24]=C:\Windows\system32\CRYPTBASE.dll
LoadedModule[25]=C:\Windows\system32\uxtheme.dll
LoadedModule[26]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System\37a1d51f35918dd36a0d4e34cc91732e\System.ni.dll
LoadedModule[27]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Core\89bc329e8c65a9e13067c9776d925d78\System.Core.ni.dll
LoadedModule[28]=C:\Windows\assembly\NativeImages_v4.0.30319_64\WindowsBase\5c4bb83974683693f279b187eae96a12\WindowsBase.ni.dll
LoadedModule[29]=C:\Windows\system32\CRYPTSP.dll
LoadedModule[30]=C:\Windows\system32\rsaenh.dll
LoadedModule[31]=C:\Windows\assembly\NativeImages_v4.0.30319_64\PresentationCore\461b892934d24d029a6ef6d42101af09\PresentationCore.ni.dll
LoadedModule[32]=C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatio5ae0f00f#\aa2d1624fcc30f9edb754a0ecec69b9d\PresentationFramework.ni.dll
LoadedModule[33]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xaml\ba63c11f9d3e97ba61001aa3e9cc585e\System.Xaml.ni.dll
LoadedModule[34]=C:\Windows\system32\dwrite.dll
LoadedModule[35]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[36]=C:\Windows\system32\MSVCP140_CLR0400.dll
LoadedModule[37]=C:\Windows\system32\OLEAUT32.dll
LoadedModule[38]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[39]=C:\Windows\system32\api-ms-win-core-xstate-l2-1-0.dll
LoadedModule[40]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll
LoadedModule[41]=C:\Windows\Microsoft.NET\Framework64\v4.0.30319\nlssorting.dll
LoadedModule[42]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Configuration\b5152c3c02957bbe4459505a39afde20\System.Configuration.ni.dll
LoadedModule[43]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Xml\1fb6db2ce6d2887fe6f8f620cb092343\System.Xml.ni.dll
LoadedModule[44]=C:\Windows\system32\shell32.dll
LoadedModule[45]=C:\Windows\system32\profapi.dll
LoadedModule[46]=C:\Windows\system32\bcrypt.dll
LoadedModule[47]=C:\Windows\system32\dwmapi.dll
LoadedModule[48]=C:\Windows\system32\RpcRtRemote.dll
LoadedModule[49]=C:\Windows\system32\Wtsapi32.dll
LoadedModule[50]=C:\Windows\system32\WINSTA.dll
LoadedModule[51]=C:\Windows\system32\d3d9.dll
LoadedModule[52]=C:\Windows\system32\d3d8thk.dll
LoadedModule[53]=C:\Windows\system32\nvd3dumx.dll
LoadedModule[54]=C:\Windows\system32\WINMM.dll
LoadedModule[55]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Drawing\7e5e0d92b127a5150606d81839f29044\System.Drawing.ni.dll
LoadedModule[56]=C:\Windows\assembly\NativeImages_v4.0.30319_64\System.Windows.Forms\028f9e8b0c8b1820df7bec952b01fe12\System.Windows.Forms.ni.dll
LoadedModule[57]=C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatiod51afaa5#\e7929a00001bdd737173fd08113e1e21\PresentationFramework.classic.ni.dll
LoadedModule[58]=C:\Windows\WinSxS\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17825_none_2b253c8271ec7765\gdiplus.dll
LoadedModule[59]=C:\Windows\system32\WindowsCodecs.dll
LoadedModule[60]=C:\Program Files\Icaros\64-bit\IcarosThumbnailProvider.dll
LoadedModule[61]=C:\Program Files\Icaros\64-bit\avcodec-ics-59.dll
LoadedModule[62]=C:\Program Files\Icaros\64-bit\avutil-ics-57.dll
LoadedModule[63]=C:\Program Files\Icaros\64-bit\avformat-ics-59.dll
LoadedModule[64]=C:\Program Files\Icaros\64-bit\swscale-ics-6.dll
LoadedModule[65]=C:\Program Files\Icaros\64-bit\IcarosCache.dll
LoadedModule[66]=C:\Program Files\Icaros\64-bit\libunarr-ics.dll
LoadedModule[67]=C:\Program Files\Icaros\64-bit\IcarosPropertyHandler.dll
LoadedModule[68]=C:\Windows\system32\PROPSYS.dll
LoadedModule[69]=C:\Windows\assembly\NativeImages_v4.0.30319_64\Presentatio49d6fefe#\40c6b063064b47abacbfe2f49ffe13f2\PresentationFramework-SystemXml.ni.dll
LoadedModule[70]=C:\Windows\system32\msasn1.dll
LoadedModule[71]=C:\Windows\system32\cryptnet.dll
LoadedModule[72]=C:\Windows\system32\CRYPT32.dll
LoadedModule[73]=C:\Windows\system32\WLDAP32.dll
LoadedModule[74]=C:\Windows\system32\drvstore.dll
LoadedModule[75]=C:\Windows\system32\devobj.dll
LoadedModule[76]=C:\Windows\system32\CFGMGR32.dll
LoadedModule[77]=C:\Windows\system32\WINTRUST.DLL
LoadedModule[78]=C:\Windows\system32\imagehlp.dll
LoadedModule[79]=C:\Windows\system32\ncrypt.dll
LoadedModule[80]=C:\Windows\system32\bcryptprimitives.dll
LoadedModule[81]=C:\Windows\system32\USERENV.dll
LoadedModule[82]=C:\Windows\assembly\NativeImages_v4.0.30319_64\UIAutomationTypes\0cc4a3aa71de035a3312471881743697\UIAutomationTypes.ni.dll
LoadedModule[83]=C:\Windows\assembly\NativeImages_v4.0.30319_64\UIAutomationProvider\d4e9732a576d7e827309d8fa413ce9fc\UIAutomationProvider.ni.dll
LoadedModule[84]=C:\Windows\system32\UIAutomationCore.dll
LoadedModule[85]=C:\Windows\system32\PSAPI.DLL
LoadedModule[86]=C:\Windows\system32\OLEACC.dll
LoadedModule[87]=C:\Windows\system32\GPAPI.dll
FriendlyEventName=Nicht mehr funktionsfähig
ConsentKey=APPCRASH
AppName=IcarosConfig
AppPath=C:\Program Files\Icaros\IcarosConfig.exe

Unfortunately, I cannot reproduce the Crash.

**Comment by Xanashi** [comment]
Thanks for the error log. 
I may have an idea what could be causing this, but error message in the above log is a bit vague,
so I hope the change I did will fix it, if other users run into the same issue.
It will be available in the next release.

**Comment by Xanashi** [comment]
Should be fixed in #63
