### ISSUE TITLE
Shell extensions... 32-bit vs. 64-bit

### ISSUE THREAD

**Issue by ctp9** [Xanashi/Icaros#66]
During installation it prompts to install 32-bit or 64-bit shell extensions. On a new system 64-bit extensions are pre-selected and cannot be unchecked, while at the same time 32-bit extensions are also checked (but can be unchecked).

Am I supposed to proceed the installation with both of them checked? Or can I go ahead with just the 64-bit extensions for my system?

**Comment by Xanashi** [comment]
Hi ctp9,

For most users on 64-bit systems, installing both shell extensions is the preferred option.

The reason why you would want the 32-bit extensions installed on your 64-bit system, is to make thumbnailing/properties
work in the 'open file' dialogs of any 32-bit application on your system. 

If you don't require thumbnailing and properties in any of your 32-bit applications, you can settle for the 64-bit extensions during installation.
