### ISSUE TITLE
mkv file tags and corresponding explorer values

### ISSUE THREAD

**Issue by paulgoulain** [Xanashi/Icaros#67]
Hi,

I've been playing with mkv files and their tags using the list from [matroska.org](https://www.matroska.org/technical/tagging.html) and I wanted to see which tags are handle by Icaros and to which explorer value they are linked.

I can see that the TITLE tag of the mkv file is correctly parsed and display in the explorer, but the ACTOR tag isn't.
Do you have a list of tags Icaros can parse and under which name they are displayed in the explorer ?

Thank you !

**Comment by Xanashi** [comment]
Hi paulgoulain,

There is no Actor property in Explorer so I don't currently handle that tag in Icaros.
The following MKV tags are handled:

TITLE
ARTIST
PART_NUMBER
SUBTITLE   
COMMENT    
COPYRIGHT  
DATE_RECORDED
DATE_RELEASED
GENRE      
MOOD       
COMPOSER   
CONDUCTOR  
PUBLISHER  
URL        
RATING     
RATING WMP 
BPM        
INITIAL_KEY

The following tags are are also handled for ALBUM variants:

TITLE
ARTIST
PART_NUMBER

Hope that helps

**Comment by paulgoulain** [comment]
Thank you for the list.

I don't know if it would make sense to consider ACTOR tag as a contributing artist in the explorer ? Also to consider KEYWORDS tag as a tag in the explorer. Those are subject to debate I guess.

Others have a direct equivalent with the explorer, like PRODUCER, DIRECTOR or even COMMENT and COPYRIGHT (although the last two are kind of exotic ^^).  Would it be interesting to implement them ?

**Comment by Xanashi** [comment]
I definitely don't mind adding KEYWORDS, PRODUCER and DIRECTOR. I'll make sure they are included in the next release.
COMMENT and COPYRIGHT are already included. ;)

ACTOR as 'contributing artist' is not quite possible, as that property is already used by the ARTIST tag.
