### ISSUE TITLE
Sometimes mkv thumbnails are not displayed for new files.

### ISSUE THREAD

**Issue by josephkarthic** [Xanashi/Icaros#69]
Whenever I download or copy a new *.mkv file, the thumbmail is not displayed, I had to deactivate thumbnailing and then activate it again in the software to properly display it, I'm using latest version and on windows 10 1909, please fix this small issue...thanks.

**Comment by Xanashi** [comment]
Hi Joseph,
What happens if you just refresh (F5) File Explorer, after the new MKV has been copied or downloaded?

**Comment by josephkarthic** [comment]
> Hi Joseph, What happens if you just refresh (F5) File Explorer, after the new MKV has been copied or downloaded?

Hi Xanashi,

Sorry I should've mentioned, I refreshed in file explorer as well as in Icaros-> tools ->refresh, Nothing happens, the thumbnail is not acquired, only after i click "thumbnailing" to deactivated and then activate again it works...I'm not sure if it happens only to me or universal...

**Comment by Xanashi** [comment]
Ok, thank you for clearing that up.
And you have to do this after every new download/copy?

**Comment by josephkarthic** [comment]
> Ok, thank you for clearing that up. And you have to do this after every new download/copy?

Yes, For every new mkv file I had to do this in  order to get the thumbnail....But if it works for you then maybe something wrong with my pc.. :)

**Comment by josephkarthic** [comment]
> Ok, thank you for clearing that up. And you have to do this after every new download/copy?

Hi Xanashi,

I uninstalled the icaros and installed it again selecting only 64 bit , and now everything works perfectly...Previously I installed both x86 and 64 bit so I think the mkv's were not shown properly...All good now...I think you can close this issue,,,thankyou for this awesome tool...🙏

**Comment by Xanashi** [comment]
Thank for the follow up!
I'm curious why only selecting the 64bit components fixed the issue for you.
I can't imagine the 32bit components having any impact on 64bit Explorer. I'll have to keep that in mind if I see this bug again.
With that said, I'm very glad you got it working again. And thanks for the kind words ❤️

**Comment by josephkarthic** [comment]
> Thank for the follow up! I'm curious why only selecting the 64bit components fixed the issue for you. I can't imagine the 32bit components having any impact on 64bit Explorer. I'll have to keep that in mind if I see this bug again. With that said, I'm very glad you got it working again. And thanks for the kind words ❤️

Hi, Im sorry to say that this issue happens again, after a restart it behaves the same, the new mkv files are not refreshed properly and no thumbnails...kindly see if you can fix this in next release...thankyou..

![2023-10-12_231808](https://github.com/Xanashi/Icaros/assets/142990481/4fa464d7-df55-4017-9628-500d5779b956)

**Comment by Xanashi** [comment]
It almost seems like another software is interfering. The fact that it works again if you deactivate then reactivate Icaros is interesting. Almost like it works until it is blocked again by something.

Do you have any other Shell Extensions installed?
Do you have any File Explorer modifications installed?
Do you have any registry cleaners that runs regularly?
Any third-party anti-virus software?

Also make sure that when you install/update software that overrides the default icons, 
that it doesn't also disable thumbnailing for those files. (Although I'm quite certain MPC-HC doesn't do that)

**Comment by clsid2** [comment]
Your download tool should use a different file extension during the download and only rename to .mkv when finished. Otherwise  Explorer may attempt to get a thumbnail for the partially downloaded file and fail. Reactivating Icaros might trigger another attempt. Just an idea as possible cause.
Mention which tool you are using as well. It could be related directly to that.

**Comment by josephkarthic** [comment]
> Do you have any other Shell Extensions installed? Do you have any File Explorer modifications installed? Do you have any registry cleaners that runs regularly? Any third-party anti-virus software?
> 

I have a shell extension program called startisback to modify windows theme appearance, I also have OldNewExplorer file explorer modification, no registry cleaner installed, no antivirus installed, I only use MPC-HC and madVR and no additional filters like LAV, I only use internal filters instead, Only this mkv is the issue all other files are displaying fine...im not sure if the above shell extensions are causing the problem..

![2023-10-13_182554](https://github.com/Xanashi/Icaros/assets/142990481/7358f85a-1f4d-4890-9214-f52624944784)

> Your download tool should use a different file extension during the download and only rename to .mkv when finished. Otherwise Explorer may attempt to get a thumbnail for the partially downloaded file and fail. Reactivating Icaros might trigger another attempt. Just an idea as possible cause. Mention which tool you are using as well. It could be related directly to that.

I only download with chrome browser, I also tested copying files from other hard drives and only the mkv are not displaying, all other files are ok...

**Comment by clsid2** [comment]
Does thumbnailing work if you rename the .mkv to .mp4?

**Comment by josephkarthic** [comment]
> Does thumbnailing work if you rename the .mkv to .mp4?

Yes it works instantly...pls see the below video

https://github.com/Xanashi/Icaros/assets/142990481/cf1bc169-6b7c-4255-a509-51f32c7881fc

**Comment by clsid2** [comment]
Use regedit.exe and go to `HKEY_CLASSES_ROOT\.mkv`

It should look like this:
```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.mkv]
"PerceivedType"="video"
"Content Type"="video/x-matroska"
@="mplayerc64.mkv"

[HKEY_CLASSES_ROOT\.mkv\shellex]

[HKEY_CLASSES_ROOT\.mkv\shellex\{BB2E617C-0920-11D1-9A0B-00C04FC2D6C1}]
@="{c5aec3ec-e812-4677-a9a7-4fee1f9aa000}"

[HKEY_CLASSES_ROOT\.mkv\shellex\{E357FCCD-A995-4576-B01F-234630154E96}]
@="{c5aec3ec-e812-4677-a9a7-4fee1f9aa000}"
```

**Comment by josephkarthic** [comment]
> Use regedit.exe and go to `HKEY_CLASSES_ROOT\.mkv`
> 
> It should look like this:
> 
> ```
> Windows Registry Editor Version 5.00
> 
> [HKEY_CLASSES_ROOT\.mkv]
> "PerceivedType"="video"
> "Content Type"="video/x-matroska"
> @="mplayerc64.mkv"
> 
> [HKEY_CLASSES_ROOT\.mkv\shellex]
> 
> [HKEY_CLASSES_ROOT\.mkv\shellex\{BB2E617C-0920-11D1-9A0B-00C04FC2D6C1}]
> @="{c5aec3ec-e812-4677-a9a7-4fee1f9aa000}"
> 
> [HKEY_CLASSES_ROOT\.mkv\shellex\{E357FCCD-A995-4576-B01F-234630154E96}]
> @="{c5aec3ec-e812-4677-a9a7-4fee1f9aa000}"
> ```

I checked it, Mine looks different as seen below...Should I delete that key and import yours instead?

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.mkv]
@=""
"Content Type"="video/x-matroska"
"KMPlayer64.bak"="mplayerc64.mkv"
"PerceivedType"="video"

[HKEY_CLASSES_ROOT\.mkv\OpenWithProgids]
"AppX6eg8h5sxqq90pv53845wmnbewywdqq5h"=hex(0):
"AppXje1yfpbq840nvc3prwa53vknqsk55vha"=hex(0):
"AppXk0g4vb8gvt7b93tg50ybcy892pge6jmt"=hex(0):
"WMP11.AssocFile.MKV"=hex(0):

[HKEY_CLASSES_ROOT\.mkv\ShellEx]

[HKEY_CLASSES_ROOT\.mkv\ShellEx\{BB2E617C-0920-11d1-9A0B-00C04FC2D6C1}]
@="{c5aec3ec-e812-4677-a9a7-4fee1f9aa000}"

[HKEY_CLASSES_ROOT\.mkv\ShellEx\{e357fccd-a995-4576-b01f-234630154e96}]
@="{c5aec3ec-e812-4677-a9a7-4fee1f9aa000}"

```

**Comment by clsid2** [comment]
No, the contents of your `ShellEx` subkey is correct.

Look at `HKEY_CLASSES_ROOT\mplayerc64.mkv` (or the ProgID of whatever file association is your current default). That key should **not** have a ShellEx subkey. If it does, remove the subkey.

Otherwise, I would suggest to temporarily uninstall OldNewExplorer to see if that is the cause.

**Comment by josephkarthic** [comment]
> No, the contents of your `ShellEx` subkey is correct.
> 
> Look at `HKEY_CLASSES_ROOT\mplayerc64.mkv` (or the ProgID of whatever file association is your current default). That key should **not** have a ShellEx subkey. If it does, remove the subkey.
> 
> Otherwise, I would suggest to temporarily uninstall OldNewExplorer to see if that is the cause.

Below is the contents of `HKEY_CLASSES_ROOT\mplayerc64.mkv`, I think there is no subkey...I also uninstalled OldNewExplorer as well as the Startisback start menu changer, but still the same... Maybe there is something else that's interrupting 

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\mplayerc64.mkv]
@="Matroska"

[HKEY_CLASSES_ROOT\mplayerc64.mkv\DefaultIcon]
@="\"C:\\Program Files\\MPC-HC\\mpciconlib.dll\",20"

[HKEY_CLASSES_ROOT\mplayerc64.mkv\shell]

[HKEY_CLASSES_ROOT\mplayerc64.mkv\shell\enqueue]
@="Add to MPC-HC Playlist"
"Icon"="\"C:\\Program Files\\MPC-HC\\mpc-hc64.exe\",0"

[HKEY_CLASSES_ROOT\mplayerc64.mkv\shell\enqueue\command]
@="\"C:\\Program Files\\MPC-HC\\mpc-hc64.exe\" /add \"%1\""

[HKEY_CLASSES_ROOT\mplayerc64.mkv\shell\open]
@="Play with MPC-HC"
"Icon"="\"C:\\Program Files\\MPC-HC\\mpc-hc64.exe\",0"

[HKEY_CLASSES_ROOT\mplayerc64.mkv\shell\open\command]
@="\"C:\\Program Files\\MPC-HC\\mpc-hc64.exe\" \"%1\""
```

**Comment by clsid2** [comment]
No issue there either.

As a test, next time you download a .mkv file with Chrome, right-click "save link as" and save it as a .mp4 file. Just to rule out the issue being related to the download process.

**Comment by Xanashi** [comment]
Thank you @clsid2 for troubleshooting! ❤️
@josephkarthic let us know the result of @clsid2 last suggestion, when you can.

**Comment by josephkarthic** [comment]
> No issue there either.
> 
> As a test, next time you download a .mkv file with Chrome, right-click "save link as" and save it as a .mp4 file. Just to rule out the issue being related to the download process.

> Thank you @clsid2 for troubleshooting! ❤️ @josephkarthic let us know the result of @clsid2 last suggestion, when you can.

Ok As I suspected earlier that the issue could be happening only to my system, I upgraded the windows 10 to latest version 22H2 and again reinstalled everything, now the problem seems to have been fixed, but I'll monitor again and let you know if it happens again...Thankyou so much both of you for your patience and support....🙏.👍

**Comment by Xanashi** [comment]
You're very welcome @josephkarthic. 👍 
I'm very happy to hear you got it working again.

I will say I have seen this issue before, but I'm not sure what is causing it. It's quite rare. 
Maybe it's related to a Windows update, who knows.
