### ISSUE TITLE
Cannot work on MP4 video encoded with h265

### ISSUE THREAD

**Issue by SunshineExpress** [Xanashi/Icaros#7]
Version: 3.0.3
OS: Windows 10 1709 (16299.64)

**Comment by Xanashi** [comment]
Do you have a sample I could download somewhere?
I assume the file doesn't thumbnail?

**Comment by SunshineExpress** [comment]
http://168.235.105.13/2c057f400e00e3dce9a7db88bb6ef489.mp4
MD5:2c057f400e00e3dce9a7db88bb6ef489

**Comment by Xanashi** [comment]
Hi SunshineExpress,

Thanks for uploading the test file. I've been troubleshooting this issue with LazyBumHorse (see referenced issue), and we may have found and fixed this issue as well.

Would you be able to send me a mail at Xanashi at gmail com? I could then provide you with a test build of Icaros, that you could try out to confirm the fix.

**Comment by SunshineExpress** [comment]
Well, it seems work correctly on 3.1.0 Beta 1.
