### ISSUE TITLE
How to uninstall portable (zip) version?

### ISSUE THREAD

**Issue by gendalv** [Xanashi/Icaros#75]
It keeps saying folder is in use when trying to just delete it. And I'm not seeing any "icaros*" process in task manager to kill.

**Comment by gendalv** [comment]
Had to exit/relog to windows user session, weird that it doesn't give you any indication of what is using it.

**Comment by clsid2** [comment]
The propertyhandler dll stays in use by explorer.exe until reboot/logoff

**Comment by Xanashi** [comment]
@clsid2 is correct.
To unlock it with IcarosConfig itself, you can run the following command:

IcarosConfig.exe -deactivate -unlock

This will also just restart explorer if the propertyhandler is in use, but no reboot/logoff is required.
