### ISSUE TITLE
3.1.0-b1 H.265 crashes COM Surrogate

### ISSUE THREAD

**Issue by LazyBumHorse** [Xanashi/Icaros#8]
Any thumbnail generation on seemingly any HEVC video causes COM Surrogate to crash for me with the following message:
```
Problem Event Name:        APPCRASH
Application Name:          DllHost.exe
Application Version:       6.1.7600.16385
Application Timestamp:     4a5bca54
Fault Module Name:         avcodec-ics-58.dll
Fault Module Version:      58.11.101.0
Fault Module Timestamp:    00000000
Exception Code:            c0000005
Exception Offset:          000000000001c07a
OS Version:                6.1.7601.2.1.0.256.49
Locale ID:                 1031
Additional Information 1:  ea60
Additional Information 2:  ea60f32a8e29fc5943d4f1ccd000898c
Additional Information 3:  6986
Additional Information 4:  69863348accbd621d83e658e7a3f1f4f 
```

I recently moved to a Ryzen system and my very old AMD system didn't have this issue (both Win7 x64).
The example file in [this issue](https://github.com/Xanashi/Icaros/issues/7) crashes for me as well.
Version 3.0.3 final does not crash (but I have at least one file with a green thumbnail).
Actually playing the files using LAV 0.71.0.34-git in MPC-HC is no issue at all.
May be some compilation issue with avcodec-ics-58.dll?

Edit: While I was at it I created a [dump](http://www.mediafire.com/file/y4gzn2oihvn2av9/) using Icaros debug mode, if that helps at all.

**Comment by Xanashi** [comment]
Could be a CPU specific issue. While testing these files in MPC-HC and LAV, are you testing with DXVA2 enabled? And you're right, it could be an issue with my current FFmpeg compilation settings. 
Interesting that 3.0.3 does not crash though. I'll will need to take a look at some of the most recent FFmpeg changes.

**Comment by LazyBumHorse** [comment]
I've tested with and without DXVA2, plays without issues.

**Comment by Xanashi** [comment]
I could try recompiling Icaros with the latest version of FFmpeg, and send you a test build.
Another thing to try: Open IcarosConfig and while staying on the thumbnailing page, hold Ctrl + Alt,
then drop the file onto the window. Does it crash? (I would assume it would). Does it give you the option to produce a minidump?

**Comment by LazyBumHorse** [comment]
It crashes and produces a 350MB dump, not exactly 'mini' :)
Uploaded it [here](http://www.mediafire.com/file/ud8sjs88d0z7pbd/).
I hope I didn't mess it up, Icaros crashed again while I wanted to upload it, so I had to redo it.

**Comment by Xanashi** [comment]
Yeah, about the "mini"-part. :D 
Think I might've overtweaked the settings for minidump outputs a little too much last time. 
Will have to turn that down a bit for the next release.
Nevertheless thanks for the quick upload, I'll take a look at it and get back to you.

**Comment by Xanashi** [comment]
Hi LazyBumHorse,
Could you send a mail at Xanashi at gmail com, that way I can send you a test build back and then 
we can see if that fixes this problem.

**Comment by LazyBumHorse** [comment]
Just sent a mail.

**Comment by LazyBumHorse** [comment]
Hm... the test build crashes as well, I made sure to uninstall the other version first.
```
Problem Event Name:        APPCRASH
Application Name:          DllHost.exe
Application Version:       6.1.7600.16385
Application Timestamp:     4a5bca54
Fault Module Name:         avcodec-ics-58.dll
Fault Module Version:      58.17.100.0
Fault Module Timestamp:    00000000
Exception Code:            c0000005
Exception Offset:          000000000001c2da
OS Version:                6.1.7601.2.1.0.256.49
Locale ID:                 1031
Additional Information 1:  ea60
Additional Information 2:  ea60f32a8e29fc5943d4f1ccd000898c
Additional Information 3:  6268
Additional Information 4:  626866084ebbb4e46567df0ca13ea125
```
Message is identical except for Fault Module Version and Additional Information 3+4.

Ctrl+Alt dropped it to create another [dump](http://www.mediafire.com/file/vlz1lr1x9h7l9zn/).

**Comment by Xanashi** [comment]
Hmm... let me compile another version and send that. Should give me some more info.

**Comment by LazyBumHorse** [comment]
Hold on, VCRUNTIME140D.dll is missing and I installed every single VC++ Redistributable there is.
Apparently the 'D' stands for debug and according to [this](https://msdn.microsoft.com/en-us/library/8kche8ah.aspx), debug builds are generally not redistributable.
Can you try and send me the file anyways? Maybe we'll get lucky.

**Comment by LazyBumHorse** [comment]
And now it's asking for ucrtbased.dll, according to Dependency Walker this should be all.
Oh, also, are we talking 64 bit?

**Comment by Xanashi** [comment]
Sent! and yep 64 bit.

**Comment by LazyBumHorse** [comment]
Worked, as in crashed. Here's the [dump](http://www.mediafire.com/file/7desdnh6sd2wejn).
I need to clean my MediaFire after this is done :)

**Comment by LazyBumHorse** [comment]
Your latest test build DIDN'T crash on the test file. In fact, I couldn't bring it to crash with any of my files!
Looks like you got it, congratulations!

**Comment by Xanashi** [comment]
Nice! Really glad to hear that. 
I assume all the files thumbnailed alright as well?

**Comment by LazyBumHorse** [comment]
From the look of it, yes!

**Comment by Xanashi** [comment]
That's great. 
I'll close up this issue then and see if the test build also works for [SunshineExpress](https://github.com/Xanashi/Icaros/issues/7).
Thanks for all your help testing this and for getting back to me so quick with both information and dump files! :+1:
