### ISSUE TITLE
[Feature Request] Support 32-bit mode PSD files

### ISSUE THREAD

**Issue by PeterPedro** [Xanashi/Icaros#80]
Just as the title says, I think it would be nice if we could have thumbnails of PSD files that were made in 32-bit mode, unless I'm missing something but it doesn't seem to be supported right now.

**Comment by Xanashi** [comment]
Could you send me 2-3 sample files saved in 32-bit mode? That would be a big help.

**Comment by Xanashi** [comment]
Since there hasn't been a follow up to this for almost a year, I'm going to close it for now. 
Don't hesitate to reopen it again with follow ups.
