### ISSUE TITLE
Hi Xanashi, Can you please offer us a way to make view ->Extra Large Icons More Larger ?

### ISSUE THREAD

**Issue by Arun10752** [Xanashi/Icaros#81]
I love how i can set custom thumbnails and how icaros is helping me to show them while windows explorer doesn't display it correctly

Now my request is , Can you provide us option to increase thumbnails size ? i want thumbnails to be bigger like yt home page.... its sad why Microsoft never innovates these things....

I want a new option View ->Extra Extra Large icons

if not possible with windows explorer... please introduce icaros explorer as a new file manager with all kind of same themes such as win 8.1/10/11

ICarors explorer can be same as windows explorer but with new additions to offer more customization and immersion

**Comment by Xanashi** [comment]
Hi Arun10752,

Unfortunately, there is no official way to modify the thumbnail sizes in Explorer, this is completely up to Microsoft. 
There is of course several apps that modify Explorer through unofficial means, but I'm not sure any of them have an
option to add custom thumbnail sizes (it would most likely break Explorer).

So your options are probably to add a request on the MS Feedback Hub, or use one of the many alternative
File Explorer solutions, that already exists. Most of them allows thumbnails of larger sizes.

While I like the idea of an Icaros Explorer, that would be an incredible undertaking, that I simply don't have the time to do.
I appreciate the suggestion though. ;)
