### ISSUE TITLE
wtf VirusTotal detect 

### ISSUE THREAD

**Issue by Ammar-A7med** [Xanashi/Icaros#83]
![image](https://github.com/Xanashi/Icaros/assets/94337602/528b59c7-7a71-45e6-af53-e6e33946b614)

**Comment by Xanashi** [comment]
I really hoped when I got these false-positives reported and fixed in 3.3.1, they would continue to work with 3.3.2,
but unfortunately that does not seem to be the case.. 
I'll try and contact those 3 vendors again. 
Thanks for letting me know.

**Comment by Ammar-A7med** [comment]
You are welcome
To clarify, I am not saying this because I doubt you or anything like that
I have already updated the program
I think virus total is a shit hole for open source world and new programs
but Thank you for this wonderful application and keep going

**Comment by Xanashi** [comment]
Thank you for kind words and thank you for letting me know about this.
I definitely prefer when my software has a clean record on VT.

Edit: I've reported the false-positve detections to the incorrect vendors now.
