### ISSUE TITLE
[Feature Request] Preview of .eps (and other vector formats) files

### ISSUE THREAD

**Issue by mpoetter** [Xanashi/Icaros#87]
Hey there,

it would be great for me to preview .eps and other vector formats in windows explorer.

Best

**Comment by Xanashi** [comment]
Icaros currently support thumbnailing of .ai and .pdf files with embedded thumbnails.
I may be able to find a similar solution for .eps files.
I'm currently working on .svg support.

**Comment by es771993** [comment]
Yes please, I need EPS thumbnailing

**Comment by Xanashi** [comment]
Duly noted 😊

**Comment by Xanashi** [comment]
I've added EPS and INDD thumbnailing in 3.3.3 Beta 2:
https://github.com/Xanashi/Icaros/releases/tag/v3.3.3b2

Let me know if it works.

**Comment by Xanashi** [comment]
I'm going to close this ticket for now. Don't hesitate to reopen it if needed.
