### ISSUE TITLE
No thumbnails on OneDrive folders

### ISSUE THREAD

**Issue by ThoAppelsin** [Xanashi/Icaros#9]
First mentioned on: http://shark007.net/forum/Thread-BUG-OneDrive-on-demand-issue-No-thumbnails-for-files-under-specific-folders

Since the Fall Creators Update 2017, thumbnails are not shown on files located in any one of the OneDrive folders by Icaros. For example, FLV files do not have thumbnails on Windows by default, but `example.flv` will have a thumbnail with Icaros if it is in a folder that is not OneDrive-synced. As soon as `example.flv` is moved into a folder synced by OneDrive, it stops displaying the thumbnail, and rather shows the icon of its player.

One thing I have realized is that text and PDF files in OneDrive folders display thumbnails, while text and PDF files in non-OneDrive folders don't have any thumbnails. I think OneDrive might be overriding the file icons of files synced through it. If that is the case, then _Icaros might not have a chance to do anything to display a thumbnail on files located in OneDrive folders_, unless there is a way to prioritize the thumbnails it provides or a flag that keeps OneDrive from messing with the thumbnails of the files with a given extension.

**Comment by Xanashi** [comment]
Hi ThoAppelsin,

It's more or less exactly as you expected.

OneDrive, and most cloud based services on Windows, has their own thumbnail providers, generating the thumbnails via the cloud.

This means that only filetypes that are currently supported by OneDrive will get thumbnails before they are downloaded and stored locally on you computer. As soon as they are placed on your drive, the shell extensions installed on your system, such as Icaros, will take over thumbnailing and property generation.

I believe a lot of users started experiencing this issue once OneDrive and Dropbox implemented the "online-only" sync options,
that allowed users to view "shadows" of their clouded files without having them downloaded to their local drives.
