### ISSUE TITLE
[Feature Request] Cache deduplication

### ISSUE THREAD

**Issue by esteban614** [Xanashi/Icaros#93]
Hey there.
As of the latest version, Icaros creates an entry in its cache for each file in the included locations, which is inefficient if many files share thumbnails.
In some scenarios, having the cache detect and deduplicate repeated entries could help reduce its overall size.
Thanks for developing this program.

**Comment by Xanashi** [comment]
Detecting duplicate thumbnails in the cache would come with a pretty significant performance hit,
as each thumbnail would need to be hashed and compared with all entries. 
So Icaros is currently prioritizing speed over size, which is kind of the purpose of the cache.
