### ISSUE TITLE
Does Icaros need to be running in order to dynamically add thumbnails to the cache?

### ISSUE THREAD

**Issue by lukeman3000** [Xanashi/Icaros#94]
I'm a little unsure of how this works; when I installed Icaros is it always running in the background even if I click the "x" and close the program? Or should/can it be minimized to the system tray so that other operations aren't interrupted?

**Comment by clsid2** [comment]
No. It does not need to run in the background.

It is a "plugin" for Explorer and gets used by Explorer only when needed.

**Comment by lukeman3000** [comment]
Thanks!

**Comment by Xanashi** [comment]
Thank you @clsid2 for answering!
Another great thing about (most) shell extensions is that, once they've completed their task, they are unloaded/freed automatically afterwards by File Explorer.
