### ISSUE TITLE
Add more/custom thumbnail options 

### ISSUE THREAD

**Issue by onyx-nxt** [Xanashi/Icaros#98]
The ability to input your own custom ffmpeg command to choose the video preview would be great. Or just add an option to use the 3rd keyframe in a video, that's what I'm trying to accomplish here

**Comment by Xanashi** [comment]
Icaros doesn't use the FFmpeg commandline interface, it's calling the FFmpeg libraries directly.
Adding an option to use the **n**th keyframe of a video would be possible, but I don't see it being used by more than a handful of users. 
The most straight forward solution would be for you to make a script that uses FFmpeg to extract the 3rd keyframe for the inputtet video(s) and then embed that keyframe as cover art in the file(s). 

1. First use your current ffmpeg.exe command to extract the frame to a png/jpg file named cover.jpg (or cover.png).
2. Then use a command like this to embed the cover.jpg into your file:

ffmpeg.exe -i input.mp4 -i cover.jpg -map 0 -map 1 -c copy -c:v:1 jpg -disposition:v:1 attached_pic output.mp4

Replace .mp4 with .mkv if necessary and .jpg with .png if necessary.

**Comment by Xanashi** [comment]
I’m closing this issue for now.
Feel welcome to reopen it if needed.
